import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

// Single flat config for the whole monorepo. Type-aware linting is deliberately
// left off: it would force every package to be built before `lint` can run and
// the untyped ruleset already covers the correctness bugs we care about.
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.turbo/**",
      "**/storybook-static/**",
      "**/coverage/**",
      "pnpm-lock.yaml",
      // SVGR output — regenerated by `pnpm icons:build`, never hand-edited.
      "packages/icons/raw/**",
      "packages/icons/src/components/**",
      "packages/icons/src/catalog.ts",
      "packages/icons/src/index.ts",
      // Synced from the external ALD token source.
      "packages/tokens/source/**",
      // Stray tsc emit next to sources (see .gitignore).
      "packages/*/src/**/*.js",
      "packages/*/src/**/*.d.ts",
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  {
    plugins: { "react-hooks": reactHooks },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.es2022 },
    },
  },

  // Classic hooks rules only. v7 `recommended` also turns on React Compiler
  // checks (set-state-in-effect, etc.) which are out of scope for this gate.
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  },

  // Build scripts, tooling and config files run in Node.
  {
    files: [
      "**/*.{mjs,cjs}",
      "**/scripts/**/*.{js,ts,mjs}",
      "**/*.config.{js,ts,mjs}",
      "apps/docs/.storybook/**/*.{ts,tsx}",
    ],
    languageOptions: {
      globals: { ...globals.node, ...globals.es2022 },
    },
  },

  {
    rules: {
      // Warn-first on hygiene rules so `lint` stays a zero-error gate while the
      // existing backlog is worked down. See docs/LINTING.md.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "no-empty": ["error", { allowEmptyCatch: true }],
      // ESLint 10 recommended; existing wheel handlers initialize then assign.
      "no-useless-assignment": "warn",
      // Correctness rules stay at error.
      "react-hooks/rules-of-hooks": "error",
      "no-console": "off",
    },
  },

  // Tests and dev-only surfaces may reach for looser typing.
  {
    files: ["**/*.test.{ts,tsx}", "apps/playground/**", "**/*.stories.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },

  // Storybook CSF: `render` is mounted as a component, so hooks inside it are
  // legal. The rule's naming heuristic cannot see that and reports every story.
  {
    files: ["**/*.stories.tsx"],
    rules: { "react-hooks/rules-of-hooks": "off" },
  },

  // Must stay last: drops every rule Prettier owns.
  prettier
);
