/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M18 21C15.2386 21 13 23.2386 13 26V82C13 84.7614 15.2386 87 18 87H35.6863C38.6037 87 41.4016 88.1589 43.4645 90.2218L56.3248 103.082C58.3112 105.069 61.5437 105.029 63.481 102.995L75.4631 90.4138C77.5392 88.2338 80.4181 87 83.4286 87H102C104.761 87 107 84.7614 107 82V26C107 23.2386 104.761 21 102 21H18ZM7 26C7 19.9249 11.9249 15 18 15H102C108.075 15 113 19.9249 113 26V82C113 88.0751 108.075 93 102 93H83.4286C82.0602 93 80.7516 93.5608 79.8079 94.5517L67.8259 107.133C63.5637 111.608 56.4522 111.695 52.0822 107.325L39.2218 94.4645C38.2841 93.5268 37.0124 93 35.6863 93H18C11.9249 93 7 88.0751 7 82V26Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M18 15C11.9249 15 7 19.9249 7 26V82C7 88.0751 11.9249 93 18 93H35.6863C37.0124 93 38.2841 93.5268 39.2218 94.4645L52.0822 107.325C56.4522 111.695 63.5637 111.608 67.8259 107.133L79.8079 94.5517C80.7516 93.5608 82.0602 93 83.4286 93H102C108.075 93 113 88.0751 113 82V26C113 19.9249 108.075 15 102 15H18Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M19 22.5C17.067 22.5 15.5 24.067 15.5 26V82C15.5 83.933 17.067 85.5 19 85.5H35.6863C39.0015 85.5 42.1809 86.817 44.5251 89.1612L57.3855 102.022C58.7759 103.412 61.0387 103.384 62.3948 101.96L74.3768 89.3793C76.7361 86.9021 80.0076 85.5 83.4286 85.5H101C102.933 85.5 104.5 83.933 104.5 82V26C104.5 24.067 102.933 22.5 101 22.5H19ZM6.5 26C6.5 19.0964 12.0964 13.5 19 13.5H101C107.904 13.5 113.5 19.0964 113.5 26V82C113.5 88.9036 107.904 94.5 101 94.5H83.4286C82.4707 94.5 81.5547 94.8926 80.8941 95.5862L68.9121 108.167C64.0687 113.253 55.9875 113.351 51.0215 108.385L38.1612 95.5251C37.5048 94.8688 36.6145 94.5 35.6863 94.5H19C12.0964 94.5 6.5 88.9036 6.5 82V26Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M19 13.5C12.0964 13.5 6.5 19.0964 6.5 26V82C6.5 88.9036 12.0964 94.5 19 94.5H35.6863C36.6145 94.5 37.5048 94.8688 38.1612 95.5251L51.0215 108.385C55.9875 113.351 64.0687 113.253 68.9121 108.167L80.8941 95.5862C81.5547 94.8926 82.4707 94.5 83.4286 94.5H101C107.904 94.5 113.5 88.9036 113.5 82V26C113.5 19.0964 107.904 13.5 101 13.5H19Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M19 22C16.7909 22 15 23.7909 15 26V82C15 84.2091 16.7909 86 19 86H35.6863C38.8689 86 41.9211 87.2643 44.1716 89.5147L57.0319 102.375C58.621 103.964 61.207 103.933 62.7569 102.305L74.7389 89.7241C77.0038 87.346 80.1445 86 83.4286 86H101C103.209 86 105 84.2091 105 82V26C105 23.7909 103.209 22 101 22H19ZM7 26C7 19.3726 12.3726 14 19 14H101C107.627 14 113 19.3726 113 26V82C113 88.6274 107.627 94 101 94H83.4286C82.3339 94 81.287 94.4487 80.532 95.2414L68.55 107.823C63.9004 112.705 56.1424 112.799 51.3751 108.032L38.5147 95.1716C37.7646 94.4214 36.7472 94 35.6863 94H19C12.3726 94 7 88.6274 7 82V26Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M19 14C12.3726 14 7 19.3726 7 26V82C7 88.6274 12.3726 94 19 94H35.6863C36.7472 94 37.7646 94.4214 38.5147 95.1716L51.3751 108.032C56.1424 112.799 63.9004 112.705 68.55 107.823L80.532 95.2414C81.287 94.4487 82.3339 94 83.4286 94H101C107.627 94 113 88.6274 113 82V26C113 19.3726 107.627 14 101 14H19Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type CommunicateCommentProps = AvialaIconProps;

export function CommunicateComment({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: CommunicateCommentProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
