/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M104.271 32.898C96.7436 20.9903 80.3068 18.7299 69.844 28.1636L62.239 35.0206C60.9667 36.1677 59.0333 36.1677 57.761 35.0206L50.156 28.1636C39.6932 18.7299 23.2564 20.9903 15.7286 32.898C9.97049 42.0063 11.4005 53.9062 19.1525 61.3909L60 100.83L100.847 61.3909C108.6 53.9061 110.03 42.0063 104.271 32.898ZM65.8262 23.7074C79.0513 11.7832 99.8276 14.6404 109.343 29.6919C116.621 41.2049 114.814 56.2465 105.015 65.7073L62.7635 106.502C61.2218 107.99 58.7782 107.99 57.2365 106.502L14.985 65.7073C5.18626 56.2465 3.37872 41.2049 10.657 29.6919C20.1724 14.6404 40.9487 11.7832 54.1738 23.7074L60 28.9606L65.8262 23.7074Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M109.343 29.6919C99.8276 14.6404 79.0513 11.7832 65.8262 23.7074L60 28.9606L54.1738 23.7074C40.9487 11.7832 20.1724 14.6404 10.657 29.6919C3.37872 41.2049 5.18626 56.2465 14.985 65.7073L57.2365 106.502C58.7782 107.99 61.2218 107.99 62.7635 106.502L105.015 65.7073C114.814 56.2465 116.621 41.2049 109.343 29.6919Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M103.07 33.0973C96.1954 22.4036 81.4319 20.3011 71.8454 28.6506L63.1871 36.1917C61.3603 37.7829 58.6397 37.7829 56.8128 36.1917L48.1546 28.6506C38.5681 20.3011 23.8045 22.4035 16.93 33.0973C11.5906 41.403 12.8111 52.3154 19.8534 59.2363L60 98.6907L100.147 59.2363C107.189 52.3154 108.409 41.403 103.07 33.0973ZM65.9344 21.8639C79.66 9.90931 100.798 12.9196 110.641 28.2305C118.285 40.1223 116.538 55.7463 106.455 65.6554L63.8468 107.529C61.7115 109.627 58.2885 109.627 56.1532 107.529L13.545 65.6554C3.46206 55.7463 1.71465 40.1223 9.35938 28.2305C19.2021 12.9196 40.34 9.90931 54.0656 21.8639L60 27.0326L65.9344 21.8639Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M110.641 28.2305C100.798 12.9196 79.66 9.90931 65.9344 21.8639L60 27.0326L54.0656 21.8639C40.34 9.90931 19.2021 12.9196 9.35938 28.2305C1.71465 40.1223 3.46206 55.7463 13.545 65.6554L56.1532 107.529C58.2885 109.627 61.7115 109.627 63.8468 107.529L106.455 65.6554C116.538 55.7463 118.285 40.1223 110.641 28.2305Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M49.7491 29.1555C39.8853 20.2782 24.401 22.4389 17.3443 33.6773C11.9659 42.2429 13.3265 53.4056 20.6048 60.4285L60 98.4414L99.3952 60.4285C106.674 53.4056 108.034 42.2429 102.656 33.6774C95.599 22.4389 80.1147 20.2782 70.251 29.1555L62.9013 35.7702C61.2519 37.2547 58.7481 37.2547 57.0987 35.7702L49.7491 29.1555ZM10.5692 29.4232C20.2668 13.979 41.5457 11.0096 55.1008 23.2092L60 27.6185L64.8992 23.2092C78.4543 11.0096 99.7333 13.979 109.431 29.4232C116.822 41.1943 114.952 56.5343 104.95 66.1855L63.4469 106.232C61.5237 108.088 58.4764 108.088 56.5531 106.232L15.0499 66.1855C5.04776 56.5343 3.17807 41.1943 10.5692 29.4232Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M55.1008 23.2092C41.5457 11.0096 20.2668 13.979 10.5692 29.4232C3.17807 41.1943 5.04776 56.5343 15.0499 66.1855L56.5531 106.232C58.4764 108.088 61.5237 108.088 63.4469 106.232L104.95 66.1855C114.952 56.5343 116.822 41.1943 109.431 29.4232C99.7333 13.979 78.4543 11.0096 64.8992 23.2092L60 27.6185L55.1008 23.2092Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type CommunicateLoveProps = AvialaIconProps;

export function CommunicateLove({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: CommunicateLoveProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
