/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M60 5C90.3757 5 115 29.6243 115 60C115 90.3757 90.3757 115 60 115C29.6243 115 5 90.3757 5 60C5 29.6243 29.6243 5 60 5ZM11 60C11 87.062 32.938 109 60 109C86.0546 109 107.359 88.6648 108.909 63H68C61.9249 63 57 58.0751 57 52V11.0908C31.3352 12.6409 11 33.9454 11 60ZM63 52C63 54.7614 65.2386 57 68 57H108.909C107.419 32.3275 87.6725 12.581 63 11.0908V52Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M63 5.08008C90.9873 6.5845 113.415 29.0127 114.919 57H68C65.2386 57 63 54.7614 63 52V5.08008Z" fill="currentColor" /><path d="M57 52C57 58.0751 61.9249 63 68 63H114.919C113.361 91.9805 89.3691 115 60 115C29.6243 115 5 90.3757 5 60C5 30.6309 28.0194 6.63789 57 5.08008V52Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M60 4.5C90.6518 4.5 115.5 29.3482 115.5 60C115.5 90.6518 90.6518 115.5 60 115.5C29.3482 115.5 4.5 90.6518 4.5 60C4.5 29.3482 29.3482 4.5 60 4.5ZM13.5 60C13.5 85.6812 34.3188 106.5 60 106.5C84.1631 106.5 104.019 88.0697 106.282 64.5H68C61.0964 64.5 55.5 58.9036 55.5 52V13.7168C31.9303 15.9802 13.5 35.8369 13.5 60ZM64.5 52C64.5 53.933 66.067 55.5 68 55.5H106.282C104.161 33.4112 86.5888 15.838 64.5 13.7168V52Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M64.5 4.68066C91.563 6.85219 113.148 28.437 115.319 55.5H68C66.067 55.5 64.5 53.933 64.5 52V4.68066Z" fill="currentColor" /><path d="M55.5 52C55.5 58.9036 61.0964 64.5 68 64.5H115.319C113.029 93.0473 89.1368 115.5 60 115.5C29.3482 115.5 4.5 90.6518 4.5 60C4.5 30.8632 26.9527 6.97129 55.5 4.68066V52Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M60 5C90.3757 5 115 29.6243 115 60C115 90.3757 90.3757 115 60 115C29.6243 115 5 90.3757 5 60C5 29.6243 29.6243 5 60 5ZM13 60C13 85.9574 34.0426 107 60 107C84.61 107 104.801 88.0851 106.831 64H68C61.3726 64 56 58.6274 56 52V13.168C31.9149 15.1978 13 35.3899 13 60ZM64 52C64 54.2091 65.7909 56 68 56H106.831C104.912 33.2335 86.7665 15.0867 64 13.168V52Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M64 5.14355C91.1873 7.0976 112.902 28.8127 114.856 56H68C65.7909 56 64 54.2091 64 52V5.14355Z" fill="currentColor" /><path d="M56 52C56 58.6274 61.3726 64 68 64H114.856C112.807 92.5083 89.0305 115 60 115C29.6243 115 5 90.3757 5 60C5 30.9695 27.4917 7.19255 56 5.14355V52Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type DataPieChartProps = AvialaIconProps;

export function DataPieChart({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DataPieChartProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
