/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M41.2363 57C41.0813 57.9772 41 58.9792 41 60C41 61.0208 41.0813 62.0228 41.2363 63H7C5.34315 63 4 61.6569 4 60C4 58.3431 5.34315 57 7 57H41.2363ZM113 57C114.657 57 116 58.3431 116 60C116 61.6569 114.657 63 113 63H78.7637C78.9187 62.0228 79 61.0208 79 60C79 58.9792 78.9187 57.9772 78.7637 57H113Z" fill="currentColor" /><path d="M73 60C73 52.8203 67.1797 47 60 47C52.8203 47 47 52.8203 47 60C47 67.1797 52.8203 73 60 73C67.1797 73 73 67.1797 73 60ZM79 60C79 70.4934 70.4934 79 60 79C49.5066 79 41 70.4934 41 60C41 49.5066 49.5066 41 60 41C70.4934 41 79 49.5066 79 60Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M35.1797 57C35.062 57.9836 35 58.9847 35 60C35 61.0153 35.062 62.0164 35.1797 63H7C5.34315 63 4 61.6569 4 60C4 58.3431 5.34315 57 7 57H35.1797ZM113 57C114.657 57 116 58.3431 116 60C116 61.6569 114.657 63 113 63H84.8203C84.938 62.0164 85 61.0153 85 60C85 58.9847 84.938 57.9836 84.8203 57H113Z" fill="currentColor" /><path d="M60 41C70.4934 41 79 49.5066 79 60C79 70.4934 70.4934 79 60 79C49.5066 79 41 70.4934 41 60C41 49.5066 49.5066 41 60 41Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M39.9971 55.5C39.6727 56.9482 39.5 58.4539 39.5 60C39.5 61.5461 39.6727 63.0518 39.9971 64.5H7C4.51472 64.5 2.5 62.4853 2.5 60C2.5 57.5147 4.51472 55.5 7 55.5H39.9971ZM113 55.5C115.485 55.5 117.5 57.5147 117.5 60C117.5 62.4853 115.485 64.5 113 64.5H80.0029C80.3273 63.0518 80.5 61.5461 80.5 60C80.5 58.4539 80.3273 56.9482 80.0029 55.5H113Z" fill="currentColor" /><path d="M71.5 60C71.5 53.6487 66.3513 48.5 60 48.5C53.6487 48.5 48.5 53.6487 48.5 60C48.5 66.3513 53.6487 71.5 60 71.5C66.3513 71.5 71.5 66.3513 71.5 60ZM80.5 60C80.5 71.3218 71.3218 80.5 60 80.5C48.6782 80.5 39.5 71.3218 39.5 60C39.5 48.6782 48.6782 39.5 60 39.5C71.3218 39.5 80.5 48.6782 80.5 60Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M32.3613 55.5C32.1246 56.9651 32 58.4681 32 60C32 61.5319 32.1246 63.0349 32.3613 64.5H7C4.51472 64.5 2.5 62.4853 2.5 60C2.5 57.5147 4.51472 55.5 7 55.5H32.3613ZM113 55.5C115.485 55.5 117.5 57.5147 117.5 60C117.5 62.4853 115.485 64.5 113 64.5H87.6387C87.8754 63.0349 88 61.5319 88 60C88 58.4681 87.8754 56.9651 87.6387 55.5H113Z" fill="currentColor" /><path d="M60 39.5C71.3218 39.5 80.5 48.6782 80.5 60C80.5 71.3218 71.3218 80.5 60 80.5C48.6782 80.5 39.5 71.3218 39.5 60C39.5 48.6782 48.6782 39.5 60 39.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M40.4004 56C40.138 57.2925 40 58.6301 40 60C40 61.3699 40.138 62.7075 40.4004 64H7C4.79086 64 3 62.2091 3 60C3 57.7909 4.79086 56 7 56H40.4004ZM113 56C115.209 56 117 57.7909 117 60C117 62.2091 115.209 64 113 64H79.5996C79.862 62.7075 80 61.3699 80 60C80 58.6301 79.862 57.2925 79.5996 56H113Z" fill="currentColor" /><path d="M72 60C72 53.3726 66.6274 48 60 48C53.3726 48 48 53.3726 48 60C48 66.6274 53.3726 72 60 72C66.6274 72 72 66.6274 72 60ZM80 60C80 71.0457 71.0457 80 60 80C48.9543 80 40 71.0457 40 60C40 48.9543 48.9543 40 60 40C71.0457 40 80 48.9543 80 60Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M33.2959 56C33.102 57.3053 33 58.6408 33 60C33 61.3592 33.102 62.6947 33.2959 64H7C4.79086 64 3 62.2091 3 60C3 57.7909 4.79086 56 7 56H33.2959ZM113 56C115.209 56 117 57.7909 117 60C117 62.2091 115.209 64 113 64H86.7041C86.898 62.6947 87 61.3592 87 60C87 58.6408 86.898 57.3053 86.7041 56H113Z" fill="currentColor" /><path d="M60 40C71.0457 40 80 48.9543 80 60C80 71.0457 71.0457 80 60 80C48.9543 80 40 71.0457 40 60C40 48.9543 48.9543 40 60 40Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type DevelopCommitProps = AvialaIconProps;

export function DevelopCommit({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DevelopCommitProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
