/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M107.113 48.8709L67.7782 9.53554C63.4824 5.23978 56.5176 5.23978 52.2218 9.53555L12.8787 48.8787C12.3358 49.4216 12 50.1716 12 51C12 52.6569 13.3431 54 15 54C15.7912 54 16.5109 53.6937 17.047 53.1932L56.5884 16.2878C56.7208 16.1643 56.8582 16.0492 57 15.9427V111C57 112.657 58.3431 114 60 114C61.6569 114 63 112.657 63 111V15.9427C63.1418 16.0492 63.2792 16.1643 63.4116 16.2878L102.95 53.1901C103.486 53.6924 104.207 54 105 54C106.657 54 108 52.6569 108 51C108 50.1676 107.661 49.4144 107.113 48.8709Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M108.164 48.3003C108.989 49.116 109.5 50.2483 109.5 51.5C109.5 53.9853 107.485 56 105 56C103.797 56 102.705 55.5282 101.897 54.7595L64.5 19.4397V110C64.5 112.485 62.4853 114.5 60 114.5C57.5147 114.5 55.5 112.485 55.5 110V19.5241L18.1088 55.2534L18.0595 55.2017C17.3328 55.7051 16.4509 56 15.5 56C13.0147 56 11 53.9853 11 51.5C11 50.5125 11.3181 49.5994 11.8573 48.8573L11.818 48.818L51.1927 9.44333C56.0549 4.58105 63.9314 4.55904 68.8208 9.39409L108.164 48.3003Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M107.828 49.1715C108.552 49.8954 109 50.8954 109 52C109 54.2091 107.209 56 105 56C103.925 56 102.949 55.5759 102.23 54.8859L64 18.3548V110C64 112.209 62.2091 114 60 114C57.7909 114 56 112.209 56 110V18.4275L18.2881 54.8682C17.5677 55.5686 16.5842 56 15.5 56C13.2909 56 11.5 54.2091 11.5 52C11.5 50.9035 11.9412 49.91 12.6558 49.1874L12.6558 49.1874L51.4991 9.90759C56.1776 5.17657 63.8122 5.15524 68.517 9.86005L107.828 49.1715Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowUpProps = AvialaIconProps;

export function DirectionArrowUp({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowUpProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
