/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M23.2907 12.1253L81.033 13.0002C82.6747 13.0178 84.0001 14.3541 84.0001 16C84.0001 17.647 82.6729 18.984 81.0297 18.9999L24.7998 19.8785C24.5865 19.8818 24.3764 19.8985 24.1704 19.9277L107.112 102.869C107.66 103.413 108 104.167 108 105C108 106.657 106.657 108 105 108C104.172 108 103.422 107.664 102.879 107.121L19.9277 24.1704C19.8985 24.3764 19.8819 24.5864 19.8785 24.7997L18.9999 81.031C18.9833 82.6736 17.6466 84 16.0001 84C14.3584 84 13.0247 82.6814 13.0004 81.0455L12.1253 23.2907C12.0313 17.0857 17.0857 12.0313 23.2907 12.1253Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M80.0348 11.5002L80.0346 11.5315C82.2678 11.7959 83.9999 13.6957 83.9999 16.0001C83.9999 18.2795 82.3051 20.1631 80.1069 20.4595L80.1079 20.4987L28.1105 21.7466L108.182 101.818L108.143 101.857C108.682 102.599 109 103.513 109 104.5C109 106.985 106.985 109 104.5 109C103.512 109 102.599 108.682 101.857 108.143L101.818 108.182L101.333 107.697C101.323 107.687 101.313 107.677 101.303 107.667L21.7604 28.1244L20.5827 80.1019L20.4988 80.1C20.4457 82.5391 18.4518 84.5001 15.9999 84.5001C13.5146 84.5001 11.4999 82.4853 11.4999 80.0001C11.4999 79.7166 11.5261 79.4393 11.5762 79.1704L11.0738 23.676C11.0105 16.6906 16.6846 11.0091 23.6701 11.0633L80.0348 11.5002Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M23.659 11.5645L79.7364 12.0085C79.8236 12.0028 79.9116 12 80.0002 12C82.2093 12 84.0002 13.7908 84.0002 16C84.0002 18.1663 82.278 19.9305 80.128 19.998L80.1284 20.0086L27.3589 21.7017L107.829 102.171L107.829 102.172C108.552 102.895 109 103.895 109 105C109 107.209 107.209 109 105 109C103.886 109 102.879 108.545 102.154 107.81L21.6956 27.3521L19.999 79.0997C19.946 81.2628 18.176 83 16.0002 83C13.797 83 12.0098 81.2187 12.0002 79.0177L12.0002 79L11.5643 23.6586C11.5116 16.9572 16.9577 11.5114 23.659 11.5645Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowLeftUpProps = AvialaIconProps;

export function DirectionArrowLeftUp({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowLeftUpProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
