/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M106.375 23.2907L105.5 81.0455C105.475 82.6814 104.142 84 102.5 84C100.859 84 99.5254 82.6821 99.5004 81.0468H99.5002L98.6213 24.7997C98.618 24.5864 98.6013 24.3764 98.5721 24.1704L15.6423 107.1C15.0978 107.655 14.3392 108 13.5 108C11.8431 108 10.5 106.657 10.5 105C10.5 104.172 10.8357 103.422 11.3786 102.879L11.3785 102.879L94.3295 19.9277C94.1234 19.8985 93.9134 19.8818 93.7 19.8785L37.4697 18.9999C35.8268 18.9836 34.5 17.6468 34.5 16C34.5 14.3541 35.8254 13.0178 37.4671 13.0002L95.2094 12.1253C101.414 12.0313 106.469 17.0857 106.375 23.2907Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M98.9594 80.1019L99.0011 80.101C99.0548 82.5396 101.048 84.5001 103.5 84.5001C105.985 84.5001 108 82.4853 108 80.0001C108 79.8046 107.988 79.6122 107.963 79.4233L108.468 23.676C108.531 16.6906 102.857 11.0091 95.8717 11.0633L39.5071 11.5002L39.5073 11.5267C37.2538 11.7721 35.5 13.6813 35.5 16.0001C35.5 18.294 37.2164 20.1871 39.4351 20.4649L39.4343 20.4987L91.4316 21.7466L12.2059 100.972C11.9341 101.188 11.6878 101.434 11.4723 101.706L11.3602 101.818L11.3751 101.833C10.8251 102.579 10.5 103.502 10.5 104.5C10.5 106.985 12.5147 109 15 109C15.9983 109 16.9206 108.675 17.667 108.125L17.7241 108.182L97.7818 28.1244L98.9594 80.1019Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M104 83C106.203 83 107.99 81.219 108 79.0183L108 79L108.436 23.6586C108.489 16.9572 103.043 11.5114 96.3412 11.5645L40.2638 12.0085C40.1766 12.0028 40.0886 12 40 12C37.7909 12 36 13.7908 36 16C36 18.1663 37.7222 19.9305 39.8722 19.998L39.8718 20.0086L92.6415 21.7017L12.1906 102.153C11.4556 102.878 11 103.886 11 105C11 107.209 12.7909 109 15 109C16.1046 109 17.1047 108.552 17.8285 107.828L17.8286 107.828L98.3046 27.3524L100.001 79.0999C100.054 81.2629 101.824 83 104 83Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowRightUpProps = AvialaIconProps;

export function DirectionArrowRightUp({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowRightUpProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
