/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M67.8068 102.953L104.712 63.4116C104.836 63.2792 104.951 63.1418 105.057 63H10C8.34315 63 7 61.6569 7 60C7 58.3431 8.34315 57 10 57H105.057C104.951 56.8582 104.836 56.7208 104.712 56.5884L67.8178 17.0586C67.3108 16.5214 67 15.797 67 15C67 13.3431 68.3431 12 70 12C70.8284 12 71.5784 12.3358 72.1213 12.8787L111.464 52.2218C115.76 56.5176 115.76 63.4824 111.464 67.7782L72.1258 107.117C71.5826 107.662 70.8307 108 70 108C68.3431 108 67 106.657 67 105C67 104.209 67.3063 103.489 67.8068 102.953Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M72.182 11.818L72.1427 11.8573C71.4006 11.3181 70.4875 11 69.5 11C67.0147 11 65 13.0147 65 15.5C65 16.4508 65.2949 17.3328 65.7982 18.0594L65.7465 18.1088L101.476 55.5H11C8.51472 55.5 6.5 57.5147 6.5 60C6.5 62.4853 8.51472 64.5 11 64.5H101.56L66.2284 101.91C65.4669 102.716 65 103.804 65 105C65 107.485 67.0147 109.5 69.5 109.5C70.7556 109.5 71.891 108.986 72.7073 108.156L111.606 68.8208C116.441 63.9314 116.419 56.0549 111.557 51.1927L72.182 11.818Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M111.092 51.4991L71.8126 12.6558C71.09 11.9412 70.0965 11.5 69 11.5C66.7909 11.5 65 13.2909 65 15.5C65 16.5845 65.4316 17.5682 66.1323 18.2887L102.573 56H11C8.79086 56 7 57.7909 7 60C7 62.2091 8.79086 64 11 64H102.645L66.1138 102.231C65.424 102.949 65 103.925 65 105C65 107.209 66.7909 109 69 109C70.1104 109 71.1151 108.548 71.8398 107.817L111.14 68.5169C115.845 63.8121 115.823 56.1775 111.092 51.4991Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowRightProps = AvialaIconProps;

export function DirectionArrowRight({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowRightProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
