/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M12 44C12 44.8325 12.3391 45.5858 12.8867 46.1293L52.2218 85.4645C56.5176 89.7602 63.4824 89.7602 67.7782 85.4645L107.121 46.1213C107.664 45.5784 108 44.8284 108 44C108 42.3431 106.657 41 105 41C104.205 41 103.482 41.3092 102.946 41.8138L63.4116 78.7122C61.4906 80.5051 58.5095 80.5051 56.5884 78.7122L17.047 41.8068L17.047 41.8068C16.5109 41.3063 15.7912 41 15 41C13.3431 41 12 42.3431 12 44Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M10.5 44.5C10.5 45.7516 11.011 46.8839 11.8358 47.6996L11.8357 47.6997L51.1791 86.6059C56.0684 91.4409 63.9449 91.4189 68.8072 86.5566L107.661 47.7024C107.675 47.6888 107.689 47.6752 107.702 47.6614L108.182 47.1819L108.143 47.1427C108.682 46.4007 109 45.4875 109 44.5C109 42.0147 106.985 40 104.5 40C103.549 40 102.667 40.2949 101.941 40.7982L101.891 40.7465L62.3858 78.496C61.0387 79.7833 58.9192 79.7895 57.5646 78.5101L18.0898 41.2284L18.0898 41.2284C17.2838 40.4669 16.1964 40 15 40C12.5147 40 10.5 42.0147 10.5 44.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M11 44C11 45.1137 11.4551 46.121 12.1895 46.8462L51.4831 86.1398C56.1879 90.8446 63.8225 90.8233 68.5009 86.0923L107.34 46.8172C108.057 46.0942 108.5 45.0989 108.5 44C108.5 41.7909 106.709 40 104.5 40C103.416 40 102.432 40.4314 101.712 41.132L62.7486 78.7818C61.2045 80.2738 58.758 80.2806 57.2056 78.7972L17.7698 41.1142C17.0511 40.4241 16.0751 40 15 40C12.7909 40 11 41.7909 11 44Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowDownLightProps = AvialaIconProps;

export function DirectionArrowDownLight({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowDownLightProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
