/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M80.1843 102.944L43.2876 63.4116C41.4946 61.4906 41.4946 58.5095 43.2876 56.5884L80.1871 17.0532C80.4023 16.8242 80.5748 16.5696 80.7046 16.2996C80.9175 15.8567 81.0148 15.3735 80.9979 14.8943C80.9715 14.1438 80.6649 13.4031 80.0842 12.8424C79.8274 12.5942 79.5373 12.4008 79.2285 12.2623C78.8387 12.0873 78.4201 12.0002 78.0021 12C77.2283 11.9996 76.4563 12.2967 75.8722 12.885L36.5353 52.2218C32.2395 56.5176 32.2395 63.4824 36.5353 67.7782L75.8705 107.113C77.0075 108.26 78.858 108.303 80.0467 107.193C80.0546 107.186 80.0625 107.178 80.0703 107.171" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M78.9063 109.482C79.9108 109.391 80.8911 108.964 81.6642 108.2C83.416 106.467 83.4469 103.652 81.7447 101.882L44.4896 62.4354C43.2103 61.0808 43.2165 58.9613 44.5037 57.6142L82.2274 18.136C83.9392 16.3752 83.9241 13.5601 82.182 11.818C81.6697 11.3057 81.0646 10.9428 80.4209 10.7292C79.961 10.5765 79.4817 10.5002 79.0028 10.5C78.4677 10.4997 77.9325 10.5942 77.4246 10.7836C76.8266 11.0065 76.2672 11.3606 75.7914 11.8447L36.4434 51.1927C31.5811 56.055 31.5591 63.9315 36.3942 68.8208L75.2729 108.136C75.6836 108.559 76.1579 108.884 76.6664 109.111C77.3743 109.426 78.1472 109.55 78.9063 109.482Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M81.844 12.6874C83.3973 14.2582 83.3832 16.7908 81.8124 18.3442L42.5326 57.1875C40.9556 58.747 40.9485 61.2918 42.5168 62.8601L81.8282 102.172C83.3903 103.734 83.3903 106.266 81.8282 107.828C80.2661 109.391 77.7335 109.391 76.1714 107.828L36.8599 68.517C32.1551 63.8122 32.1764 56.1776 36.9075 51.4991L76.1872 12.6558C77.758 11.1025 80.2907 11.1166 81.844 12.6874Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowLeftLightProps = AvialaIconProps;

export function DirectionArrowLeftLight({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowLeftLightProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
