/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M10.5 15.5C10.5 13.8431 11.8431 12.5 13.5 12.5C14.3392 12.5 15.0979 12.8446 15.6423 13.3999L98.5721 96.3297C98.6013 96.1236 98.618 95.9136 98.6213 95.7003L99.5002 39.4532L99.5004 39.4532C99.5254 37.8179 100.859 36.5 102.5 36.5C104.142 36.5 105.475 37.8186 105.5 39.4545L106.375 97.2093C106.469 103.414 101.414 108.469 95.2094 108.375L37.4671 107.5C35.8254 107.482 34.5 106.146 34.5 104.5C34.5 102.853 35.8268 101.516 37.4697 101.5L93.7 100.622C93.9134 100.618 94.1235 100.602 94.3295 100.572L11.3785 17.6213L11.3786 17.6212C10.8357 17.0783 10.5 16.3284 10.5 15.5Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M10 16.5C10 14.0147 12.0147 12 14.5 12C15.7534 12 16.887 12.5124 17.703 13.3391L97.7817 93.3785L98.9594 41.3982L99.0011 41.3991C99.0548 38.9604 101.048 37 103.5 37C105.985 37 108 39.0147 108 41.5C108 41.6954 107.988 41.8879 107.963 42.0767L108.468 97.824C108.531 104.809 102.857 110.491 95.8717 110.437L39.5188 110C39.5126 110 39.5063 110 39.5 110C37.0147 110 35 107.985 35 105.5C35 103.018 37.0101 101.005 39.4915 101L91.4316 99.7534L11.7059 20.0277C10.6666 19.2034 10 17.9295 10 16.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M17.9479 13.7963C17.2167 12.9995 16.1667 12.5 15 12.5C12.7909 12.5 11 14.2909 11 16.5C11 17.606 11.4489 18.6071 12.1744 19.3312L92.6419 99.8036L39.8718 101.497L39.872 101.502C37.7221 101.57 36 103.334 36 105.5C36 107.709 37.7909 109.5 40 109.5C40.0595 109.5 40.1187 109.499 40.1776 109.496L96.3412 109.941C103.043 109.994 108.489 104.548 108.436 97.8468L108 42.4739L107.972 42.4741C107.991 42.3186 108 42.1604 108 42C108 39.7909 106.209 38 104 38C101.791 38 100 39.7909 100 42C100 42.1264 100.006 42.2514 100.017 42.3748L100.002 42.3743L98.3046 94.153L17.9479 13.7963Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowRightDownProps = AvialaIconProps;

export function DirectionArrowRightDown({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowRightDownProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
