/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M39.8264 102.932L76.7124 63.4116C78.5054 61.4905 78.5054 58.5094 76.7124 56.5884L39.8303 17.0718C39.3159 16.5333 39 15.8035 39 15C39 13.3431 40.3431 12 42 12C42.8285 12 43.5785 12.3358 44.1214 12.8788L44.1215 12.8787L83.4647 52.2218C87.7605 56.5176 87.7605 63.4824 83.4647 67.7782L44.1215 107.121L44.1214 107.121C43.5785 107.664 42.8285 108 42 108C40.3431 108 39 106.657 39 105C39 104.199 39.3143 103.47 39.8264 102.932Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M44.6873 12.3233L83.5566 51.1927C88.4189 56.0549 88.4409 63.9314 83.6059 68.8208L44.7126 108.151C43.896 108.984 42.7583 109.5 41.5 109.5C39.0147 109.5 37 107.485 37 105C37 103.792 37.4762 102.695 38.2512 101.886L75.5104 62.4354C76.7897 61.0808 76.7835 58.9613 75.4963 57.6142L37.7467 18.1088L37.7983 18.0595C37.2949 17.3329 37 16.4509 37 15.5C37 13.0147 39.0147 11 41.5 11C42.4874 11 43.4006 11.318 44.1426 11.8573L44.1819 11.818L44.6767 12.3127L44.6873 12.3233Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M37 15.5C37 16.5842 37.4314 17.5677 38.1319 18.2882L75.7818 57.2514C77.2738 58.7955 77.2806 61.242 75.7972 62.7944L38.1141 102.23C37.4241 102.949 37 103.925 37 105C37 107.209 38.7909 109 41 109C42.1046 109 43.1047 108.552 43.8285 107.828L43.8286 107.828L83.1401 68.5169C87.8449 63.8121 87.8235 56.1775 83.0925 51.4991L43.8128 12.6558L43.8126 12.6559C43.0901 11.9412 42.0966 11.5 41 11.5C38.7909 11.5 37 13.2909 37 15.5Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowRightLightProps = AvialaIconProps;

export function DirectionArrowRightLight({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowRightLightProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
