/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M108 15.5C108 13.8431 106.657 12.5 105 12.5C104.172 12.5 103.422 12.8358 102.879 13.3787L19.9277 96.3297C19.8985 96.1236 19.8819 95.9136 19.8785 95.7003L18.9999 39.469C18.9833 37.8265 17.6466 36.5 16.0001 36.5C14.3584 36.5 13.0247 37.8186 13.0004 39.4545H13.0004L12.1253 97.2093C12.0313 103.414 17.0857 108.469 23.2907 108.375L81.033 107.5C82.6747 107.482 84.0001 106.146 84.0001 104.5C84.0001 102.853 82.6729 101.516 81.0297 101.5L24.7998 100.622C24.5865 100.618 24.3764 100.602 24.1704 100.572L107.113 17.6302C107.661 17.0866 108 16.3329 108 15.5Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M108.182 19.682C108.996 18.8676 109.5 17.7426 109.5 16.5C109.5 14.0147 107.485 12 105 12C103.75 12 102.618 12.5099 101.803 13.333L21.7604 93.3757L20.5827 41.3982L20.4988 41.4001C20.4457 38.9609 18.4518 37 15.9999 37C13.5146 37 11.4999 39.0147 11.4999 41.5C11.4999 41.7834 11.5261 42.0607 11.5762 42.3296L11.0738 97.824C11.0105 104.809 16.6846 110.491 23.6701 110.437L80.0348 110C82.504 109.981 84.4999 107.974 84.4999 105.5C84.4999 103.041 82.5273 101.042 80.078 101.001L28.1105 99.7534L108.182 19.682Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M102.049 13.7992C102.781 13.0007 103.832 12.5 105 12.5C107.209 12.5 109 14.2909 109 16.5C109 17.6059 108.551 18.607 107.826 19.3311L107.828 19.3338L27.3587 99.8036L80.1281 101.497L80.1279 101.502C82.2778 101.57 84 103.334 84 105.5C84 107.709 82.2091 109.5 80 109.5C79.9404 109.5 79.8812 109.499 79.8223 109.496L23.6588 109.941C16.9574 109.994 11.5113 104.548 11.5641 97.8468L12 42.5L12 42.4913C12.0046 40.2862 13.7937 38.5 16 38.5C18.1814 38.5 19.955 40.2463 19.9991 42.4172L21.6954 94.1532L102.049 13.7992Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowLeftDownProps = AvialaIconProps;

export function DirectionArrowLeftDown({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowLeftDownProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
