/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M57 104.057C56.8582 103.951 56.7208 103.836 56.5884 103.712L17.047 66.8068C16.511 66.3063 15.7912 66 15 66C13.3431 66 12 67.3431 12 69C12 69.8322 12.3388 70.5852 12.8861 71.1287L52.2218 110.464C56.5176 114.76 63.4824 114.76 67.7782 110.464L107.121 71.1213C107.664 70.5784 108 69.8284 108 69C108 67.3431 106.657 66 105 66C104.205 66 103.483 66.309 102.946 66.8134L63.4116 103.712C63.2792 103.836 63.1418 103.951 63 104.057V9C63 7.34315 61.6569 6 60 6C58.3431 6 57 7.34315 57 9V104.057Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M18.0898 65.2284C17.2838 64.4669 16.1964 64 15 64C12.5147 64 10.5 66.0147 10.5 68.5C10.5 69.758 11.0162 70.8955 11.8484 71.7121L51.1792 110.606C56.0686 115.441 63.9451 115.419 68.8073 110.557L107.676 71.6875L107.687 71.6765L108.182 71.1819L108.143 71.1426C108.682 70.4006 109 69.4874 109 68.5C109 66.0147 106.985 64 104.5 64C103.549 64 102.667 64.2949 101.941 64.7982L101.891 64.7465L64.5 100.476V10C64.5 7.51472 62.4853 5.5 60 5.5C57.5147 5.5 55.5 7.51472 55.5 10V100.56L18.0898 65.2284L18.0898 65.2284Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M17.7701 65.1144C17.0513 64.4242 16.0752 64 15 64C12.7909 64 11 65.7909 11 68C11 69.1135 11.455 70.1207 12.1891 70.8459L51.4831 110.14C56.1879 114.845 63.8225 114.823 68.5009 110.092L107.339 70.818C108.057 70.095 108.5 69.0993 108.5 68C108.5 65.7909 106.709 64 104.5 64C103.416 64 102.432 64.4314 101.712 65.132L64 101.573V10C64 7.79086 62.2091 6 60 6C57.7909 6 56 7.79086 56 10V101.645L17.7701 65.1144Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowDownProps = AvialaIconProps;

export function DirectionArrowDown({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowDownProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
