/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M102.953 81.1932L63.4116 44.2878C61.4905 42.4949 58.5094 42.4949 56.5884 44.2878L17.0546 81.186C16.5178 81.6908 15.795 82 15 82C13.3431 82 12 80.6569 12 79C12 78.1716 12.3358 77.4216 12.8787 76.8787L52.2218 37.5355C56.5176 33.2398 63.4824 33.2398 67.7782 37.5355L107.114 76.8714C107.661 77.4149 108 78.1679 108 79C108 80.6569 106.657 82 105 82C104.209 82 103.489 81.6937 102.953 81.1932Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M101.897 80.759L62.4354 43.4898C61.0808 42.2104 58.9613 42.2166 57.6142 43.5038L18.1088 81.2534L18.0595 81.2017C17.3328 81.7051 16.4509 82 15.5 82C13.0147 82 11 79.9853 11 77.5C11 76.5126 11.318 75.5994 11.8573 74.8574L11.818 74.8181L12.3127 74.3233L12.3233 74.3127L51.1927 35.4434C56.0549 30.5811 63.9314 30.5591 68.8208 35.3941L108.152 74.2878C108.984 75.1045 109.5 76.2419 109.5 77.5C109.5 79.9853 107.485 82 105 82C103.797 82 102.704 81.528 101.897 80.759Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M102.231 80.8862L62.7944 43.2028C61.242 41.7194 58.7955 41.7262 57.2514 43.2182L18.2879 80.8684C17.5675 81.5687 16.5841 82 15.5 82C13.2909 82 11.5 80.2091 11.5 78C11.5 76.9006 11.9435 75.9048 12.6614 75.1818L51.4991 35.9077C56.1775 31.1767 63.8121 31.1554 68.5169 35.8602L107.811 75.1542C108.545 75.8794 109 76.8866 109 78C109 80.2091 107.209 82 105 82C103.925 82 102.949 81.576 102.231 80.8862Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type DirectionArrowUpLightProps = AvialaIconProps;

export function DirectionArrowUpLight({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: DirectionArrowUpLightProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
