/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M18 57V12C18 9.23858 20.2386 7 23 7C25.7614 7 28 9.23858 28 12V57C28 66.1325 31.4416 73.2463 36.9473 78.1289C42.5145 83.0661 50.5209 86 60 86C77.8996 86 92 74.5962 92 57V12C92 9.23858 94.2386 7 97 7C99.7614 7 102 9.23858 102 12V57C102 81.3774 82.074 96 60 96C48.4924 96 37.9985 92.4273 30.3125 85.6113C22.565 78.7407 18 68.8542 18 57Z" fill="currentColor" /><path d="M101 103C103.761 103 106 105.239 106 108C106 110.761 103.761 113 101 113H19C16.2386 113 14 110.761 14 108C14 105.239 16.2386 103 19 103H101Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M20 57V12C20 10.3431 21.3431 9 23 9C24.6569 9 26 10.3431 26 12V57C26 66.6769 29.666 74.3457 35.6201 79.626C41.6111 84.9389 50.1152 88 60 88C78.7345 88 94 75.9525 94 57V12C94 10.3431 95.3431 9 97 9C98.6569 9 100 10.3431 100 12V57C100 80.0212 81.2391 94 60 94C48.898 94 38.9019 90.5546 31.6396 84.1143C24.3405 77.6412 20 68.3099 20 57Z" fill="currentColor" /><path d="M101 105C102.657 105 104 106.343 104 108C104 109.657 102.657 111 101 111H19C17.3431 111 16 109.657 16 108C16 106.343 17.3431 105 19 105H101Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M18.5 57V12C18.5 9.51472 20.5147 7.5 23 7.5C25.4853 7.5 27.5 9.51472 27.5 12V57C27.5 66.2684 30.9976 73.5209 36.6152 78.5029C42.2884 83.5341 50.4195 86.5 60 86.5C78.1084 86.5 92.5 74.9353 92.5 57V12C92.5 9.51472 94.5147 7.5 97 7.5C99.4853 7.5 101.5 9.51472 101.5 12V57C101.5 81.0383 81.8653 95.5 60 95.5C48.5939 95.5 38.2246 91.9592 30.6445 85.2373C23.0091 78.466 18.5 68.7181 18.5 57Z" fill="currentColor" /><path d="M101 103.5C103.485 103.5 105.5 105.515 105.5 108C105.5 110.485 103.485 112.5 101 112.5H19C16.5147 112.5 14.5 110.485 14.5 108C14.5 105.515 16.5147 103.5 19 103.5H101Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M19 57V12C19 9.79086 20.7909 8 23 8C25.2091 8 27 9.79086 27 12V57C27 66.4047 30.5543 73.7955 36.2842 78.877C42.0633 84.002 50.318 87 60 87C78.3171 87 93 75.2744 93 57V12C93 9.79086 94.7909 8 97 8C99.2091 8 101 9.79086 101 12V57C101 80.6993 81.6566 95 60 95C48.6951 95 38.4497 91.4905 30.9756 84.8623C23.4525 78.1905 19 68.5818 19 57Z" fill="currentColor" /><path d="M101 104C103.209 104 105 105.791 105 108C105 110.209 103.209 112 101 112H19C16.7909 112 15 110.209 15 108C15 105.791 16.7909 104 19 104H101Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type EditUnderlineProps = AvialaIconProps;

export function EditUnderline({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: EditUnderlineProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
