/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M89.7705 8.99336C90.8789 7.76199 92.7754 7.66238 94.0068 8.77071L109.052 22.3107C113.024 25.8859 113.024 32.1145 109.052 35.6896L94.0068 49.2296L93.8896 49.3302C92.6578 50.3309 90.8443 50.1998 89.7705 49.007C88.6968 47.8139 88.7564 45.9962 89.8809 44.8761L89.9932 44.7707L104.182 32.0002H50C30.67 32.0002 15 47.6702 15 67.0001C15.0002 86.3299 30.6702 102 50 102H103C104.657 102 106 103.343 106 105C106 106.657 104.657 108 103 108H50C27.3565 108 9.00021 89.6436 9 67.0001C9 44.3565 27.3563 26.0002 50 26.0002H104.182L89.9932 13.2297C88.7618 12.1213 88.6623 10.2248 89.7705 8.99336Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M88.7705 8.99336C89.8789 7.76199 91.7754 7.66238 93.0068 8.77071L108.052 22.3107C112.024 25.8859 112.024 32.1145 108.052 35.6896L93.0068 49.2297L92.8896 49.3302C91.6578 50.3309 89.8443 50.1998 88.7705 49.007C87.6968 47.8139 87.7564 45.9962 88.8809 44.8761L88.9932 44.7707L101.516 33.5002H50C31.4985 33.5002 16.5 48.4986 16.5 67.0001C16.5002 85.5015 31.4986 100.5 50 100.5H101C103.485 100.5 105.5 102.515 105.5 105C105.5 107.485 103.485 109.5 101 109.5H50C26.528 109.5 7.50021 90.472 7.5 67.0001C7.5 43.5281 26.5279 24.5002 50 24.5002H101.516L88.9932 13.2297C87.7618 12.1213 87.6623 10.2248 88.7705 8.99336Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M88.7705 8.99336C89.8789 7.76199 91.7754 7.66238 93.0068 8.77071L108.052 22.3107C112.024 25.8859 112.024 32.1145 108.052 35.6896L93.0068 49.2297L92.8896 49.3302C91.6578 50.3309 89.8443 50.1998 88.7705 49.007C87.6968 47.8139 87.7564 45.9962 88.8809 44.8761L88.9932 44.7707L102.071 33.0002H50C31.2223 33.0002 16 48.2225 16 67.0001C16.0002 85.7776 31.2224 101 50 101H101C103.209 101 105 102.791 105 105C105 107.209 103.209 109 101 109H50C26.8042 109 8.00021 90.1959 8 67.0001C8 43.8042 26.804 25.0002 50 25.0002H102.071L88.9932 13.2297C87.7618 12.1213 87.6623 10.2248 88.7705 8.99336Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type EditUndoProps = AvialaIconProps;

export function EditUndo({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: EditUndoProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
