/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M102 108V66.2215C98.4794 69.1638 94.6379 71.2794 89.9571 72.8543C88.3868 73.3826 86.6847 72.5379 86.1564 70.9676C85.6282 69.3974 86.473 67.6962 88.0431 67.1678C94.0325 65.1526 98.3167 62.1783 102.724 57.0457C103.541 56.0936 104.865 55.7505 106.042 56.1863C107.219 56.6222 108 57.7448 108 58.9998V108C108 109.657 106.657 111 105 111C103.343 111 102 109.657 102 108Z" fill="currentColor" /><path d="M74 108C74 109.657 72.6569 111 71 111C69.3431 111 68 109.657 68 108V64.9248H18L18 108C18 109.657 16.6569 111 15 111C13.3431 111 12 109.657 12 108L12 11C12 9.34315 13.3431 8 15 8C16.6569 8 18 9.34315 18 11V58.9248H68V11C68 9.34315 69.3431 8 71 8C72.6569 8 74 9.34315 74 11V108Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M100.5 108V69.2628C97.5073 71.3689 94.2348 72.9979 90.4344 74.2765C88.079 75.0687 85.5277 73.8017 84.7352 71.4464C83.9427 69.0909 85.2097 66.5388 87.5653 65.7462C93.2766 63.8246 97.3388 61.0147 101.586 56.0685C102.812 54.6404 104.798 54.1266 106.563 54.7804C108.328 55.4344 109.5 57.1178 109.5 59.0001V108C109.5 110.485 107.485 112.5 105 112.5C102.515 112.5 100.5 110.485 100.5 108Z" fill="currentColor" /><path d="M75.5 108C75.5 110.485 73.4853 112.5 71 112.5C68.5147 112.5 66.5 110.485 66.5 108V66.4248H19.5V108C19.5 110.485 17.4853 112.5 15 112.5C12.5147 112.5 10.5 110.485 10.5 108V11C10.5 8.51472 12.5147 6.5 15 6.5C17.4853 6.5 19.5 8.51472 19.5 11V57.4248H66.5V11C66.5 8.51472 68.5147 6.5 71 6.5C73.4853 6.5 75.5 8.51472 75.5 11V108Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M101 108V68.2853C97.8322 70.6447 94.3637 72.4273 90.2753 73.8029C88.1817 74.5071 85.9135 73.3808 85.2089 71.2873C84.5045 69.1935 85.6308 66.9244 87.7246 66.2199C93.5285 64.2671 97.6646 61.4029 101.965 56.3947C103.055 55.1252 104.821 54.668 106.39 55.2492C107.959 55.8304 109 57.327 109 59.0002V108C109 110.209 107.209 112 105 112C102.791 112 101 110.209 101 108Z" fill="currentColor" /><path d="M75 108C75 110.209 73.2091 112 71 112C68.7909 112 67 110.209 67 108V65.9248H19V108C19 110.209 17.2091 112 15 112C12.7909 112 11 110.209 11 108L11 11C11 8.79086 12.7909 7 15 7C17.2091 7 19 8.79086 19 11V57.9248H67V11C67 8.79086 68.7909 7 71 7C73.2091 7 75 8.79086 75 11V108Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type EditHeadline1Props = AvialaIconProps;

export function EditHeadline1({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: EditHeadline1Props) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
