/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M58.2129 7L88 7C89.6569 7 91 8.34315 91 10C91 11.6569 89.6569 13 88 13H75.9912L50.2314 107H61.7871C63.444 107 64.7871 108.343 64.7871 110C64.7871 111.657 63.444 113 61.7871 113H32C30.3431 113 29 111.657 29 110C29 108.343 30.3431 107 32 107H44.0098L69.7695 13L58.2129 13C56.556 13 55.2129 11.6569 55.2129 10C55.2129 8.34315 56.556 7 58.2129 7Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M58.2129 5.5L88 5.5C90.4853 5.5 92.5 7.51472 92.5 10C92.5 12.4853 90.4853 14.5 88 14.5L77.1348 14.5L52.1973 105.5H61.7871C64.2724 105.5 66.2871 107.515 66.2871 110C66.2871 112.485 64.2724 114.5 61.7871 114.5H32C29.5147 114.5 27.5 112.485 27.5 110C27.5 107.515 29.5147 105.5 32 105.5H42.8662L67.8037 14.5H58.2129C55.7276 14.5 53.7129 12.4853 53.7129 10C53.7129 7.51472 55.7276 5.5 58.2129 5.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M58.2129 6L88 6C90.2091 6 92 7.79086 92 10C92 12.2091 90.2091 14 88 14L76.7539 14L51.542 106H61.7871C63.9962 106 65.7871 107.791 65.7871 110C65.7871 112.209 63.9962 114 61.7871 114H32C29.7909 114 28 112.209 28 110C28 107.791 29.7909 106 32 106H43.2471L68.459 14H58.2129C56.0038 14 54.2129 12.2091 54.2129 10C54.2129 7.79086 56.0038 6 58.2129 6Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type EditFontItalianProps = AvialaIconProps;

export function EditFontItalian({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: EditFontItalianProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
