/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M28 18C28 15.2386 30.2386 13 33 13H55H56.5858C56.6956 13 56.801 13.0436 56.8787 13.1213C56.9564 13.199 57 13.3044 57 13.4142V37C57 43.0751 61.9249 48 68 48H91.5858C91.6956 48 91.801 48.0436 91.8787 48.1213C91.9564 48.199 92 48.3044 92 48.4142V50V102C92 104.761 89.7614 107 87 107H33C30.2386 107 28 104.761 28 102V18ZM98 50V102C98 108.075 93.0751 113 87 113H33C26.9249 113 22 108.075 22 102V18C22 11.9249 26.9249 7 33 7H55H56.6863C59.6037 7 62.4016 8.15893 64.4645 10.2218L94.7782 40.5355C96.8411 42.5984 98 45.3963 98 48.3137V50ZM87.7574 42L63 17.2426V37C63 39.7614 65.2386 42 68 42H87.7574Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M57 7.00447V37C57 43.0751 61.9249 48 68 48H97.9955C97.9985 48.1044 98 48.209 98 48.3137V102C98 108.075 93.0751 113 87 113H33C26.9249 113 22 108.075 22 102V18C22 11.9249 26.9249 7 33 7H56.6863C56.791 7 56.8956 7.00149 57 7.00447ZM63 8.99233V37C63 39.7614 65.2386 42 68 42H96.0077C95.6436 41.4805 95.2328 40.9902 94.7782 40.5355L64.4645 10.2218C64.0098 9.76717 63.5195 9.35643 63 8.99233Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M29.5 19C29.5 17.067 31.067 15.5 33 15.5H55H55.5V38C55.5 44.9036 61.0964 50.5 68 50.5H90.5V51V101C90.5 102.933 88.933 104.5 87 104.5H33C31.067 104.5 29.5 102.933 29.5 101V19ZM99.5 51V101C99.5 107.904 93.9036 113.5 87 113.5H33C26.0964 113.5 20.5 107.904 20.5 101V19C20.5 12.0964 26.0964 6.5 33 6.5H55H56.6863C60.0015 6.5 63.1809 7.81696 65.5251 10.1612L95.8388 40.4749C98.183 42.8191 99.5 45.9985 99.5 49.3137V51ZM84.136 41.5L64.5 21.864V38C64.5 39.933 66.067 41.5 68 41.5H84.136Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M55.5 6.5V38C55.5 44.9036 61.0964 50.5 68 50.5H99.5V101C99.5 107.904 93.9036 113.5 87 113.5H33C26.0964 113.5 20.5 107.904 20.5 101V19C20.5 12.0964 26.0964 6.5 33 6.5H55.5ZM64.5 9.2431V11.1863V38C64.5 39.933 66.067 41.5 68 41.5H96.7569C96.4713 41.1434 96.165 40.801 95.8388 40.4749L65.5251 10.1612L64.5 11.1863L65.5251 10.1612C65.199 9.835 64.8566 9.52872 64.5 9.2431Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M29 19C29 16.7909 30.7909 15 33 15H55H56V38C56 44.6274 61.3726 50 68 50H91V51V101C91 103.209 89.2091 105 87 105H33C30.7909 105 29 103.209 29 101V19ZM99 51V101C99 107.627 93.6274 113 87 113H33C26.3726 113 21 107.627 21 101V19C21 12.3726 26.3726 7 33 7H55H56.6863C59.8689 7 62.9211 8.26428 65.1716 10.5147L95.4853 40.8284C97.7357 43.0789 99 46.1311 99 49.3137V51ZM85.3431 42L64 20.6569V38C64 40.2091 65.7909 42 68 42H85.3431Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M56 7V38C56 44.6274 61.3726 50 68 50H99V101C99 107.627 93.6274 113 87 113H33C26.3726 113 21 107.627 21 101V19C21 12.3726 26.3726 7 33 7H56ZM64 9.48628V38C64 40.2091 65.7909 42 68 42H96.5137C96.1984 41.5898 95.8551 41.1983 95.4853 40.8284L65.1716 10.5147C64.8017 10.1449 64.4102 9.80163 64 9.48628Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type FilesNormalFileProps = AvialaIconProps;

export function FilesNormalFile({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: FilesNormalFileProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
