/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M42.835 11C46.4243 11.0001 49.7883 12.7518 51.8467 15.6924L61.0693 28.8672L61.251 29.1113C62.1958 30.3003 63.6354 30.9999 65.165 31H102C108.075 31 113 35.9249 113 42V98C113 104.075 108.075 109 102 109H18C11.9249 109 7 104.075 7 98V22C7 15.9249 11.9249 11 18 11H42.835ZM18 37C15.2386 37 13 39.2386 13 42V98C13 100.761 15.2386 103 18 103H102C104.761 103 107 100.761 107 98V42C107 39.2386 104.761 37 102 37H18ZM18 17C15.2386 17 13 19.2386 13 22V32.2031C14.5005 31.4358 16.199 31 18 31H55.2383L46.9307 19.1328C45.9951 17.7963 44.4664 17.0001 42.835 17H18Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M102 31C108.075 31 113 35.9249 113 42V98C113 104.075 108.075 109 102 109H18C11.9249 109 7 104.075 7 98V42C7 35.9249 11.9249 31 18 31H102ZM43.5234 11C46.5724 11 49.485 12.2652 51.5654 14.4941L61.3711 25H18C13.8048 25 9.96495 26.5202 7 29.0391V22C7 15.9249 11.9249 11 18 11H43.5234Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M42.835 9.5C46.9138 9.50007 50.7361 11.4905 53.0752 14.832L63.3428 29.5H101C107.904 29.5 113.5 35.0964 113.5 42V98C113.5 104.904 107.904 110.5 101 110.5H19C12.0964 110.5 6.5 104.904 6.5 98V22C6.5 15.0964 12.0964 9.5 19 9.5H42.835ZM19 38.5C17.067 38.5 15.5 40.067 15.5 42V98C15.5 99.933 17.067 101.5 19 101.5H101C102.933 101.5 104.5 99.933 104.5 98V42C104.5 40.067 102.933 38.5 101 38.5H19ZM19 18.5C17.067 18.5 15.5 20.067 15.5 22V29.9971C16.6106 29.6738 17.785 29.5 19 29.5H52.3564L45.7021 19.9932C45.0472 19.0576 43.977 18.5001 42.835 18.5H19Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M101 29.5C107.904 29.5 113.5 35.0964 113.5 42V98C113.5 104.904 107.904 110.5 101 110.5H19C12.0964 110.5 6.5 104.904 6.5 98V42C6.5 35.0964 12.0964 29.5 19 29.5H101ZM43.6035 9.5C46.9948 9.5 50.2411 10.8777 52.5967 13.3174L60.9805 22H19C14.27 22 9.92408 23.6427 6.5 26.3877V22C6.5 15.0964 12.0964 9.5 19 9.5H43.6035Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M42.835 10C46.7506 10.0001 50.4205 11.9103 52.666 15.1182L61.8887 28.2939L62.0342 28.4893C62.7901 29.4402 63.9415 29.9999 65.165 30H101C107.627 30 113 35.3726 113 42V98C113 104.627 107.627 110 101 110H19C12.3726 110 7 104.627 7 98V22C7 15.3726 12.3726 10 19 10H42.835ZM19 38C16.7909 38 15 39.7909 15 42V98C15 100.209 16.7909 102 19 102H101C103.209 102 105 100.209 105 98V42C105 39.7909 103.209 38 101 38H19ZM19 18C16.7909 18 15 19.7909 15 22V30.6855C16.2514 30.2431 17.5971 30 19 30H53.3164L46.1113 19.7061C45.3628 18.6369 44.14 18.0001 42.835 18H19Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M101 30C107.627 30 113 35.3726 113 42V98C113 104.627 107.627 110 101 110H19C12.3726 110 7 104.627 7 98V42C7 35.3726 12.3726 30 19 30H101ZM43.5312 10C46.8504 10 50.0212 11.3752 52.29 13.7979L60.9082 23H19C14.4487 23 10.2718 24.601 7 27.2695V22C7 15.3726 12.3726 10 19 10H43.5312Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type FilesFolderProps = AvialaIconProps;

export function FilesFolder({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: FilesFolderProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
