/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M10.8889 18C10.8889 16.3431 12.2321 15 13.8889 15H109.889C111.546 15 112.889 16.3431 112.889 18C112.889 19.6569 111.546 21 109.889 21H13.8889C12.2321 21 10.8889 19.6569 10.8889 18ZM10.8889 60C10.8889 58.3431 12.2321 57 13.8889 57H109.889C111.546 57 112.889 58.3431 112.889 60C112.889 61.6569 111.546 63 109.889 63H13.8889C12.2321 63 10.8889 61.6569 10.8889 60ZM13.8889 99C12.2321 99 10.8889 100.343 10.8889 102C10.8889 103.657 12.2321 105 13.8889 105H109.889C111.546 105 112.889 103.657 112.889 102C112.889 100.343 111.546 99 109.889 99H13.8889Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M7 18C7 15.2386 9.23858 13 12 13H108C110.761 13 113 15.2386 113 18C113 20.7614 110.761 23 108 23H12C9.23858 23 7 20.7614 7 18ZM7 60C7 57.2386 9.23858 55 12 55H108C110.761 55 113 57.2386 113 60C113 62.7614 110.761 65 108 65H12C9.23858 65 7 62.7614 7 60ZM12 97C9.23858 97 7 99.2386 7 102C7 104.761 9.23858 107 12 107H108C110.761 107 113 104.761 113 102C113 99.2386 110.761 97 108 97H12Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M8 18C8 15.7909 9.79086 14 12 14H108C110.209 14 112 15.7909 112 18C112 20.2091 110.209 22 108 22H12C9.79086 22 8 20.2091 8 18ZM8 60C8 57.7909 9.79086 56 12 56H108C110.209 56 112 57.7909 112 60C112 62.2091 110.209 64 108 64H12C9.79086 64 8 62.2091 8 60ZM12 98C9.79086 98 8 99.7909 8 102C8 104.209 9.79086 106 12 106H108C110.209 106 112 104.209 112 102C112 99.7909 110.209 98 108 98H12Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type GeneralMenuProps = AvialaIconProps;

export function GeneralMenu({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: GeneralMenuProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
