/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M116 73V48C116 45.2386 113.761 43 111 43C108.239 43 106 45.2386 106 48V73C106 75.7614 108.239 78 111 78C113.761 78 116 75.7614 116 73Z" fill="currentColor" /><path d="M99 85V35C99 32.2386 96.7614 30 94 30C91.2386 30 89 32.2386 89 35V85C89 87.7614 91.2386 90 94 90C96.7614 90 99 87.7614 99 85Z" fill="currentColor" /><path d="M82 105V15C82 12.2386 79.7614 10 77 10C74.2386 10 72 12.2386 72 15V105C72 107.761 74.2386 110 77 110C79.7614 110 82 107.761 82 105Z" fill="currentColor" /><path d="M65 81V39C65 36.2386 62.7614 34 60 34C57.2386 34 55 36.2386 55 39V81C55 83.7614 57.2386 86 60 86C62.7614 86 65 83.7614 65 81Z" fill="currentColor" /><path d="M38 78V43C38 40.2386 40.2386 38 43 38C45.7614 38 48 40.2386 48 43V78C48 80.7614 45.7614 83 43 83C40.2386 83 38 80.7614 38 78Z" fill="currentColor" /><path d="M31 91V29C31 26.2386 28.7614 24 26 24C23.2386 24 21 26.2386 21 29V91C21 93.7614 23.2386 96 26 96C28.7614 96 31 93.7614 31 91Z" fill="currentColor" /><path d="M14 73V48C14 45.2386 11.7614 43 9 43C6.23858 43 4 45.2386 4 48V73C4 75.7614 6.23858 78 9 78C11.7614 78 14 75.7614 14 73Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M76 12C74.3431 12 73 13.3431 73 15V105C73 106.657 74.3431 108 76 108C77.6569 108 79 106.657 79 105V15C79 13.3431 77.6569 12 76 12Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M28 26C26.3431 26 25 27.3431 25 29V91C25 92.6569 26.3431 94 28 94C29.6569 94 31 92.6569 31 91V29C31 27.3431 29.6569 26 28 26Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M92 32C90.3431 32 89 33.3431 89 35V85C89 86.6569 90.3431 88 92 88C93.6569 88 95 86.6569 95 85V35C95 33.3431 93.6569 32 92 32Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M60 36C58.3431 36 57 37.3431 57 39V81C57 82.6569 58.3431 84 60 84C61.6569 84 63 82.6569 63 81V39C63 37.3431 61.6569 36 60 36Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M44 40C45.6569 40 47 41.3431 47 43V78C47 79.6569 45.6569 81 44 81C42.3431 81 41 79.6569 41 78V43C41 41.3431 42.3431 40 44 40Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M12 45C10.3431 45 9 46.3431 9 48V73C9 74.6569 10.3431 76 12 76C13.6569 76 15 74.6569 15 73V48C15 46.3431 13.6569 45 12 45Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M108 45C106.343 45 105 46.3431 105 48V73C105 74.6569 106.343 76 108 76C109.657 76 111 74.6569 111 73V48C111 46.3431 109.657 45 108 45Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M77 10.5C74.5147 10.5 72.5 12.5147 72.5 15V105C72.5 107.485 74.5147 109.5 77 109.5C79.4853 109.5 81.5 107.485 81.5 105V15C81.5 12.5147 79.4853 10.5 77 10.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M26 24.5C23.5147 24.5 21.5 26.5147 21.5 29V91C21.5 93.4853 23.5147 95.5 26 95.5C28.4853 95.5 30.5 93.4853 30.5 91V29C30.5 26.5147 28.4853 24.5 26 24.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M94 30.5C91.5147 30.5 89.5 32.5147 89.5 35V85C89.5 87.4853 91.5147 89.5 94 89.5C96.4853 89.5 98.5 87.4853 98.5 85V35C98.5 32.5147 96.4853 30.5 94 30.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M60 34.5C57.5147 34.5 55.5 36.5147 55.5 39V81C55.5 83.4853 57.5147 85.5 60 85.5C62.4853 85.5 64.5 83.4853 64.5 81V39C64.5 36.5147 62.4853 34.5 60 34.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M43 38.5C45.4853 38.5 47.5 40.5147 47.5 43V78C47.5 80.4853 45.4853 82.5 43 82.5C40.5147 82.5 38.5 80.4853 38.5 78V43C38.5 40.5147 40.5147 38.5 43 38.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M9 43.5C6.51472 43.5 4.5 45.5147 4.5 48V73C4.5 75.4853 6.51472 77.5 9 77.5C11.4853 77.5 13.5 75.4853 13.5 73V48C13.5 45.5147 11.4853 43.5 9 43.5Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M111 43.5C108.515 43.5 106.5 45.5147 106.5 48V73C106.5 75.4853 108.515 77.5 111 77.5C113.485 77.5 115.5 75.4853 115.5 73V48C115.5 45.5147 113.485 43.5 111 43.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M77 11C74.7909 11 73 12.7909 73 15V105C73 107.209 74.7909 109 77 109C79.2091 109 81 107.209 81 105V15C81 12.7909 79.2091 11 77 11Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M26 25C23.7909 25 22 26.7909 22 29V91C22 93.2091 23.7909 95 26 95C28.2091 95 30 93.2091 30 91V29C30 26.7909 28.2091 25 26 25Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M94 31C91.7909 31 90 32.7909 90 35V85C90 87.2091 91.7909 89 94 89C96.2091 89 98 87.2091 98 85V35C98 32.7909 96.2091 31 94 31Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M60 35C57.7909 35 56 36.7909 56 39V81C56 83.2091 57.7909 85 60 85C62.2091 85 64 83.2091 64 81V39C64 36.7909 62.2091 35 60 35Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M43 39C45.2091 39 47 40.7909 47 43V78C47 80.2091 45.2091 82 43 82C40.7909 82 39 80.2091 39 78V43C39 40.7909 40.7909 39 43 39Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M9 44C6.79086 44 5 45.7909 5 48V73C5 75.2091 6.79086 77 9 77C11.2091 77 13 75.2091 13 73V48C13 45.7909 11.2091 44 9 44Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M111 44C108.791 44 107 45.7909 107 48V73C107 75.2091 108.791 77 111 77C113.209 77 115 75.2091 115 73V48C115 45.7909 113.209 44 111 44Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type GeneralVoiceProps = AvialaIconProps;

export function GeneralVoice({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: GeneralVoiceProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
