/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 6C61.6569 6 63 7.34315 63 9V90.541C63.2029 90.3884 63.3972 90.2188 63.5801 90.0312L96.8516 55.9053L96.8525 55.9062C97.3974 55.3475 98.1579 55 99 55C100.657 55 102 56.3431 102 58C102 58.7759 101.702 59.4801 101.219 60.0127L101.222 60.0156L68.1475 96.4814C63.7818 101.295 56.2182 101.295 51.8525 96.4814L18.7783 60.0156L18.7803 60.0127C18.2971 59.4802 18 58.7757 18 58C18 56.3431 19.3431 55 21 55C21.8418 55 22.6016 55.3478 23.1465 55.9062L23.1484 55.9053L56.4199 90.0312C56.6028 90.2188 56.7971 90.3884 57 90.541V9C57 7.34315 58.3431 6 60 6Z" fill="currentColor" /><path d="M90 105C91.6569 105 93 106.343 93 108C93 109.657 91.6569 111 90 111H30C28.3431 111 27 109.657 27 108C27 106.343 28.3431 105 30 105H90Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 5.5C62.4853 5.5 64.5 7.51472 64.5 10V83.7393L94.9854 51.6904C95.1466 51.489 95.3246 51.3018 95.5176 51.1309L95.7393 50.8984L95.7666 50.9248C96.5243 50.3446 97.4719 50 98.5 50C100.985 50 103 52.0147 103 54.5C103 55.4091 102.729 56.2543 102.266 56.9619L102.333 57.0234L69.2246 93.5273C64.2832 98.9756 55.729 99.0005 50.7559 93.5811L17.6846 57.543V57.542C16.9492 56.741 16.5 55.6731 16.5 54.5C16.5 52.0147 18.5147 50 21 50C22.2729 50 23.4217 50.5293 24.2402 51.3789H24.2412L55.5 83.8389V10C55.5 7.51472 57.5147 5.5 60 5.5Z" fill="currentColor" /><path d="M90 103C92.7614 103 95 105.239 95 108C95 110.761 92.7614 113 90 113H30C27.2386 113 25 110.761 25 108C25 105.239 27.2386 103 30 103H90Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 6C62.2091 6 64 7.79086 64 10V86.8965L95.584 53.2617C96.3136 52.485 97.3502 52 98.5 52C100.709 52 102.5 53.7909 102.5 56C102.5 57.025 102.114 57.9592 101.479 58.667L101.48 58.668L68.9014 95.0547C64.1521 100.358 55.8562 100.385 51.0732 95.1113L18.0371 58.6875V58.6865C17.3929 57.9765 17 57.0343 17 56C17 53.7909 18.7909 52 21 52C22.1404 52 23.1678 52.4785 23.8965 53.2441L23.8984 53.2432L56 86.9912V10C56 7.79086 57.7909 6 60 6Z" fill="currentColor" /><path d="M90 104C92.2091 104 94 105.791 94 108C94 110.209 92.2091 112 90 112H30C27.7909 112 26 110.209 26 108C26 105.791 27.7909 104 30 104H90Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type GeneralDownloadProps = AvialaIconProps;

export function GeneralDownload({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: GeneralDownloadProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
