/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M44 8C63.8823 8 80 24.1177 80 44C80 52.8611 76.7957 60.9721 71.4863 67.2441L110.121 105.879C111.293 107.05 111.293 108.95 110.121 110.121C108.95 111.293 107.05 111.293 105.879 110.121L67.2441 71.4863C60.9721 76.7957 52.8611 80 44 80C24.1177 80 8 63.8823 8 44C8 24.1177 24.1177 8 44 8ZM44 14C27.4315 14 14 27.4315 14 44C14 60.5685 27.4315 74 44 74C60.5685 74 74 60.5685 74 44C74 27.4315 60.5685 14 44 14Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M44.5 7.5C64.9345 7.5 81.5 24.0655 81.5 44.5C81.5 53.0956 78.5676 61.0056 73.6504 67.2871L109.182 102.818C110.939 104.576 110.939 107.424 109.182 109.182C107.424 110.939 104.576 110.939 102.818 109.182L67.2871 73.6504C61.0056 78.5676 53.0956 81.5 44.5 81.5C24.0655 81.5 7.5 64.9345 7.5 44.5C7.5 24.0655 24.0655 7.5 44.5 7.5ZM44.5 16.5C29.036 16.5 16.5 29.036 16.5 44.5C16.5 59.964 29.036 72.5 44.5 72.5C59.964 72.5 72.5 59.964 72.5 44.5C72.5 29.036 59.964 16.5 44.5 16.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M44.5 8C64.6584 8 81 24.3416 81 44.5C81 53.1382 77.9964 61.0733 72.9805 67.3242L109.828 104.172C111.39 105.734 111.39 108.266 109.828 109.828C108.266 111.39 105.734 111.39 104.172 109.828L67.3242 72.9805C61.0733 77.9964 53.1382 81 44.5 81C24.3416 81 8 64.6584 8 44.5C8 24.3416 24.3416 8 44.5 8ZM44.5 16C28.7599 16 16 28.7599 16 44.5C16 60.2401 28.7599 73 44.5 73C60.2401 73 73 60.2401 73 44.5C73 28.7599 60.2401 16 44.5 16Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type GeneralSearchProps = AvialaIconProps;

export function GeneralSearch({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: GeneralSearchProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
