/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M44.46 7.31622C46.8593 4.88491 50.9999 6.58389 51 9.99981V110C51 111.657 49.6569 113 48 113C46.3431 113 45 111.657 45 110V17.0369L13.0771 47.6649L13.0742 47.662C12.5352 48.1792 11.8061 48.4998 11 48.4998C9.34315 48.4998 8 47.1567 8 45.4998C8.00004 44.6786 8.33063 43.9351 8.86523 43.3934L8.86426 43.3924L44.46 7.31622Z" fill="currentColor" /><path d="M72 7C73.6569 7 75 8.34315 75 10V102.963L106.923 72.335L106.925 72.3369C107.464 71.8197 108.194 71.5 109 71.5C110.657 71.5 112 72.8431 112 74.5C112 75.3212 111.668 76.0637 111.134 76.6055L111.136 76.6074L75.54 112.684C73.1407 115.115 69 113.416 69 110V10C69 8.34315 70.3431 7 72 7Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M43.3916 6.26322C46.7329 2.87675 52.5 5.24316 52.5 10.0005V110.001C52.4998 112.486 50.4851 114.501 48 114.501C45.5149 114.501 43.5002 112.486 43.5 110.001V20.5542L14.1152 48.7476L14.1133 48.7456C13.3048 49.5214 12.209 50.0005 11 50.0005C8.51487 50.0005 6.50025 47.9856 6.5 45.5005C6.5 44.2523 7.00829 43.1224 7.8291 42.3072L43.3916 6.26322Z" fill="currentColor" /><path d="M72 5.5C74.4853 5.5 76.5 7.51472 76.5 10V99.4463L105.885 71.2529L105.886 71.2539C106.694 70.478 107.791 70 109 70C111.485 70 113.5 72.0147 113.5 74.5C113.5 75.7317 113.004 76.8466 112.202 77.6592L112.203 77.6602L76.6084 113.737C73.2671 117.124 67.5 114.757 67.5 110V10C67.5 7.51472 69.5147 5.5 72 5.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M43.748 6.61408C46.7753 3.54609 51.9999 5.68969 52 9.99982V110C52 112.209 50.2091 114 48 114C45.7909 114 44 112.209 44 110V19.3817L13.7695 48.3866L13.7676 48.3846C13.0489 49.0743 12.0748 49.4999 11 49.4999C8.79086 49.4999 7 47.709 7 45.4999C7.00004 44.405 7.43963 43.4125 8.15234 42.6903L43.748 6.61408Z" fill="currentColor" /><path d="M72 6C74.2091 6 76 7.79086 76 10V100.618L106.23 71.6133L106.231 71.6143C106.95 70.9246 107.925 70.5 109 70.5C111.209 70.5 113 72.2909 113 74.5C113 75.5949 112.559 76.5863 111.847 77.3086L111.848 77.3096L76.252 113.386C73.2246 116.454 68 114.31 68 110V10C68 7.79086 69.7909 6 72 6Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type GeneralTransmissionProps = AvialaIconProps;

export function GeneralTransmission({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: GeneralTransmissionProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
