/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M15 18.4305C15.0001 9.96279 24.1667 4.67033 31.5 8.90412L103.5 50.4734C110.833 54.7074 110.833 65.2923 103.5 69.5262L31.5 111.095C24.1667 115.329 15.0001 110.037 15 101.569V18.4305ZM28.5 14.1004C25.1667 12.176 21.0001 14.5816 21 18.4305V101.569C21.0001 105.418 25.1667 107.824 28.5 105.899L100.5 64.3299C103.833 62.4054 103.833 57.5942 100.5 55.6697L28.5 14.1004Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M15 18.4305C15.0001 9.96279 24.1667 4.67033 31.5 8.90412L103.5 50.4734C110.833 54.7074 110.833 65.2923 103.5 69.5262L31.5 111.095C24.1667 115.329 15.0001 110.037 15 101.569V18.4305Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14 19.2969C14 9.67435 24.4167 3.66042 32.75 8.47167L103.25 49.1748C111.453 53.9109 111.581 65.6401 103.635 70.5947L103.25 70.8252L32.75 111.528C24.4167 116.34 14 110.326 14 100.703V19.2969ZM28.25 16.2656C25.9167 14.9185 23 16.6026 23 19.2969V100.703C23 103.397 25.9167 105.081 28.25 103.734L98.75 63.0312L98.9619 62.8994C101.081 61.4759 101.01 58.2738 98.75 56.9687L28.25 16.2656Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14 19.2969C14 9.67435 24.4167 3.66042 32.75 8.47167L103.25 49.1748C111.453 53.9109 111.581 65.6401 103.635 70.5947L103.25 70.8252L32.75 111.528C24.4167 116.34 14 110.326 14 100.703V19.2969Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14.5 19.2974C14.5 10.0598 24.5 4.28611 32.5 8.90481L103 49.6079C110.875 54.1546 110.998 65.415 103.369 70.1713L103 70.393L32.5 111.096C24.5001 115.715 14.5001 109.941 14.5 100.704V19.2974ZM28.5 15.8335C25.8333 14.2939 22.5 16.2182 22.5 19.2974V100.704C22.5001 103.783 25.8334 105.707 28.5 104.167L98.9999 63.4643L99.2421 63.3139C101.664 61.6871 101.583 58.0282 98.9999 56.5366L28.5 15.8335Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14.5 19.2974C14.5 10.0598 24.5 4.28611 32.5 8.90481L103 49.6079C110.875 54.1546 110.998 65.415 103.369 70.1713L103 70.393L32.5 111.096C24.5001 115.715 14.5001 109.941 14.5 100.704V19.2974Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type MediaVideoProps = AvialaIconProps;

export function MediaVideo({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: MediaVideoProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
