/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M34 7C27.9249 7 23 11.9249 23 18V23H18C11.9249 23 7 27.9249 7 34V86C7 92.0751 11.9249 97 18 97H23V102C23 108.075 27.9249 113 34 113H86C92.0751 113 97 108.075 97 102V97H102C108.075 97 113 92.0751 113 86V34C113 27.9249 108.075 23 102 23H97V18C97 11.9249 92.0751 7 86 7H34ZM91 23V18C91 15.2386 88.7614 13 86 13H34C31.2386 13 29 15.2386 29 18V23H91ZM29 29H91V91H29V29ZM23 29H18C15.2386 29 13 31.2386 13 34V86C13 88.7614 15.2386 91 18 91H23V29ZM29 97V102C29 104.761 31.2386 107 34 107H86C88.7614 107 91 104.761 91 102V97H29ZM97 91V29H102C104.761 29 107 31.2386 107 34V86C107 88.7614 104.761 91 102 91H97Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M34 6.5C27.0964 6.5 21.5 12.0964 21.5 19V21.5H19C12.0964 21.5 6.5 27.0964 6.5 34V86C6.5 92.9036 12.0964 98.5 19 98.5H21.5V101C21.5 107.904 27.0964 113.5 34 113.5H86C92.9036 113.5 98.5 107.904 98.5 101V98.5H101C107.904 98.5 113.5 92.9036 113.5 86V34C113.5 27.0964 107.904 21.5 101 21.5H98.5V19C98.5 12.0964 92.9036 6.5 86 6.5H34ZM89.5 21.5V19C89.5 17.067 87.933 15.5 86 15.5H34C32.067 15.5 30.5 17.067 30.5 19V21.5H89.5ZM30.5 30.5H89.5V89.5H30.5V30.5ZM21.5 30.5H19C17.067 30.5 15.5 32.067 15.5 34V86C15.5 87.933 17.067 89.5 19 89.5H21.5V30.5ZM30.5 98.5V101C30.5 102.933 32.067 104.5 34 104.5H86C87.933 104.5 89.5 102.933 89.5 101V98.5H30.5ZM98.5 89.5V30.5H101C102.933 30.5 104.5 32.067 104.5 34V86C104.5 87.933 102.933 89.5 101 89.5H98.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M34 7C27.3726 7 22 12.3726 22 19V22H19C12.3726 22 7 27.3726 7 34V86C7 92.6274 12.3726 98 19 98H22V101C22 107.627 27.3726 113 34 113H86C92.6274 113 98 107.627 98 101V98H101C107.627 98 113 92.6274 113 86V34C113 27.3726 107.627 22 101 22H98V19C98 12.3726 92.6274 7 86 7H34ZM90 22V19C90 16.7909 88.2091 15 86 15H34C31.7909 15 30 16.7909 30 19V22H90ZM30 30H90V90H30V30ZM22 30H19C16.7909 30 15 31.7909 15 34V86C15 88.2091 16.7909 90 19 90H22V30ZM30 98V101C30 103.209 31.7909 105 34 105H86C88.2091 105 90 103.209 90 101V98H30ZM98 90V30H101C103.209 30 105 31.7909 105 34V86C105 88.2091 103.209 90 101 90H98Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type PlaceholderPlaceholderProps = AvialaIconProps;

export function PlaceholderPlaceholder({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: PlaceholderPlaceholderProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
