/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M31 36C31 19.9837 43.9837 7 60 7C76.0163 7 89 19.9837 89 36V44H98C104.075 44 109 48.9249 109 55V101C109 107.075 104.075 112 98 112H22C15.9249 112 11 107.075 11 101V55C11 48.9249 15.9249 44 22 44H31V36ZM37 50H31H22C19.2386 50 17 52.2386 17 55V101C17 103.761 19.2386 106 22 106H98C100.761 106 103 103.761 103 101V55C103 52.2386 100.761 50 98 50H89H83H37ZM83 44H37V36C37 23.2975 47.2975 13 60 13C72.7025 13 83 23.2975 83 36V44ZM60 66C58.3431 66 57 67.3431 57 69V87C57 88.6569 58.3431 90 60 90C61.6569 90 63 88.6569 63 87V69C63 67.3431 61.6569 66 60 66Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M31 36C31 19.9837 43.9837 7 60 7C76.0163 7 89 19.9837 89 36V44H98C104.075 44 109 48.9249 109 55V101C109 107.075 104.075 112 98 112H22C15.9249 112 11 107.075 11 101V55C11 48.9249 15.9249 44 22 44H31V36ZM37 44H83V36C83 23.2975 72.7025 13 60 13C47.2975 13 37 23.2975 37 36V44ZM57 69C57 67.3431 58.3431 66 60 66C61.6569 66 63 67.3431 63 69V87C63 88.6569 61.6569 90 60 90C58.3431 90 57 88.6569 57 87V69Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 6.5C43.1553 6.5 29.5 20.1553 29.5 37V42.5H23C16.0964 42.5 10.5 48.0964 10.5 55V101C10.5 107.904 16.0964 113.5 23 113.5H97C103.904 113.5 109.5 107.904 109.5 101V55C109.5 48.0964 103.904 42.5 97 42.5H90.5V37C90.5 20.1553 76.8447 6.5 60 6.5ZM81.5 37V42.5H38.5V37C38.5 25.1259 48.1259 15.5 60 15.5C71.8741 15.5 81.5 25.1259 81.5 37ZM23 51.5C21.067 51.5 19.5 53.067 19.5 55V101C19.5 102.933 21.067 104.5 23 104.5H97C98.933 104.5 100.5 102.933 100.5 101V55C100.5 53.067 98.933 51.5 97 51.5H23ZM55.5 69C55.5 66.5147 57.5147 64.5 60 64.5C62.4853 64.5 64.5 66.5147 64.5 69V87C64.5 89.4853 62.4853 91.5 60 91.5C57.5147 91.5 55.5 89.4853 55.5 87V69Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M29.5 37C29.5 20.1553 43.1553 6.5 60 6.5C76.8447 6.5 90.5 20.1553 90.5 37V42.5H97C103.904 42.5 109.5 48.0964 109.5 55V101C109.5 107.904 103.904 113.5 97 113.5H23C16.0964 113.5 10.5 107.904 10.5 101V55C10.5 48.0964 16.0964 42.5 23 42.5H29.5V37ZM38.5 42.5H81.5V37C81.5 25.1259 71.8741 15.5 60 15.5C48.1259 15.5 38.5 25.1259 38.5 37V42.5ZM55.5 69C55.5 66.5147 57.5147 64.5 60 64.5C62.4853 64.5 64.5 66.5147 64.5 69V87C64.5 89.4853 62.4853 91.5 60 91.5C57.5147 91.5 55.5 89.4853 55.5 87V69Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M30 37C30 20.4315 43.4315 7 60 7C76.5685 7 90 20.4315 90 37V43H97C103.627 43 109 48.3726 109 55V101C109 107.627 103.627 113 97 113H23C16.3726 113 11 107.627 11 101V55C11 48.3726 16.3726 43 23 43H30V37ZM38 43H82V37C82 24.8497 72.1503 15 60 15C47.8497 15 38 24.8497 38 37V43ZM23 51C20.7909 51 19 52.7909 19 55V101C19 103.209 20.7909 105 23 105H97C99.2091 105 101 103.209 101 101V55C101 52.7909 99.2091 51 97 51H23ZM60 65C57.7909 65 56 66.7909 56 69V87C56 89.2091 57.7909 91 60 91C62.2091 91 64 89.2091 64 87V69C64 66.7909 62.2091 65 60 65Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M30 37C30 20.4315 43.4315 7 60 7C76.5685 7 90 20.4315 90 37V43H97C103.627 43 109 48.3726 109 55V101C109 107.627 103.627 113 97 113H23C16.3726 113 11 107.627 11 101V55C11 48.3726 16.3726 43 23 43H30V37ZM38 43H82V37C82 24.8497 72.1503 15 60 15C47.8497 15 38 24.8497 38 37V43ZM56 69C56 66.7909 57.7909 65 60 65C62.2091 65 64 66.7909 64 69V87C64 89.2091 62.2091 91 60 91C57.7909 91 56 89.2091 56 87V69Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SafetyLockOnProps = AvialaIconProps;

export function SafetyLockOn({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SafetyLockOnProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
