/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M39 9C46.1797 9 52 14.8203 52 22V98C52 105.18 46.1797 111 39 111H21C13.8203 111 8 105.18 8 98V22C8 14.8203 13.8203 9 21 9H39ZM21 19C19.3431 19 18 20.3431 18 22V98C18 99.6569 19.3431 101 21 101H39C40.6569 101 42 99.6569 42 98V22C42 20.3431 40.6569 19 39 19H21Z" fill="currentColor" /><path fillRule="evenodd" clipRule="evenodd" d="M99 9C106.18 9 112 14.8203 112 22V98C112 105.18 106.18 111 99 111H81C73.8203 111 68 105.18 68 98V22C68 14.8203 73.8203 9 81 9H99ZM81 19C79.3431 19 78 20.3431 78 22V98C78 99.6569 79.3431 101 81 101H99C100.657 101 102 99.6569 102 98V22C102 20.3431 100.657 19 99 19H81Z" fill="currentColor" /></svg>;

const BoldFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M38 9C45.1797 9 51 14.8203 51 22V98C51 105.18 45.1797 111 38 111H21C13.8203 111 8 105.18 8 98V22C8 14.8203 13.8203 9 21 9H38Z" fill="currentColor" /><path d="M99 9C106.18 9 112 14.8203 112 22V98C112 105.18 106.18 111 99 111H82C74.8203 111 69 105.18 69 98V22C69 14.8203 74.8203 9 82 9H99Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M43 11C49.0751 11 54 15.9249 54 22V98C54 104.075 49.0751 109 43 109H22C15.9249 109 11 104.075 11 98V22C11 15.9249 15.9249 11 22 11H43ZM98 11C104.075 11 109 15.9249 109 22V98C109 104.075 104.075 109 98 109H77C70.9249 109 66 104.075 66 98V22C66 15.9249 70.9249 11 77 11H98ZM22 17C19.2386 17 17 19.2386 17 22V98C17 100.761 19.2386 103 22 103H43C45.7614 103 48 100.761 48 98V22C48 19.2386 45.7614 17 43 17H22ZM77 17C74.2386 17 72 19.2386 72 22V98C72 100.761 74.2386 103 77 103H98C100.761 103 103 100.761 103 98V22C103 19.2386 100.761 17 98 17H77Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M43 11C49.0751 11 54 15.9249 54 22V98C54 104.075 49.0751 109 43 109H22C15.9249 109 11 104.075 11 98V22C11 15.9249 15.9249 11 22 11H43ZM98 11C104.075 11 109 15.9249 109 22V98C109 104.075 104.075 109 98 109H77C70.9249 109 66 104.075 66 98V22C66 15.9249 70.9249 11 77 11H98Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M40 9.5C46.9036 9.5 52.5 15.0964 52.5 22V98C52.5 104.904 46.9036 110.5 40 110.5H22C15.0964 110.5 9.5 104.904 9.5 98V22C9.5 15.0964 15.0964 9.5 22 9.5H40ZM98 9.5C104.904 9.5 110.5 15.0964 110.5 22V98C110.5 104.904 104.904 110.5 98 110.5H80C73.0964 110.5 67.5 104.904 67.5 98V22C67.5 15.0964 73.0964 9.5 80 9.5H98ZM22 18.5C20.067 18.5 18.5 20.067 18.5 22V98C18.5 99.933 20.067 101.5 22 101.5H40C41.933 101.5 43.5 99.933 43.5 98V22C43.5 20.067 41.933 18.5 40 18.5H22ZM80 18.5C78.067 18.5 76.5 20.067 76.5 22V98C76.5 99.933 78.067 101.5 80 101.5H98C99.933 101.5 101.5 99.933 101.5 98V22C101.5 20.067 99.933 18.5 98 18.5H80Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M39.3223 9.50391C46.0769 9.67484 51.5 15.2042 51.5 22V98C51.5 104.904 45.9036 110.5 39 110.5H22C15.0964 110.5 9.5 104.904 9.5 98V22C9.5 15.0964 15.0964 9.5 22 9.5H39L39.3223 9.50391ZM98.3223 9.50391C105.077 9.67484 110.5 15.2042 110.5 22V98C110.5 104.904 104.904 110.5 98 110.5H81C74.0964 110.5 68.5 104.904 68.5 98V22C68.5 15.0964 74.0964 9.5 81 9.5H98L98.3223 9.50391Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M42 10C48.6274 10 54 15.3726 54 22V98C54 104.627 48.6274 110 42 110H22C15.3726 110 10 104.627 10 98V22C10 15.3726 15.3726 10 22 10H42ZM98 10C104.627 10 110 15.3726 110 22V98C110 104.627 104.627 110 98 110H78C71.3726 110 66 104.627 66 98V22C66 15.3726 71.3726 10 78 10H98ZM22 18C19.7909 18 18 19.7909 18 22V98C18 100.209 19.7909 102 22 102H42C44.2091 102 46 100.209 46 98V22C46 19.7909 44.2091 18 42 18H22ZM78 18C75.7909 18 74 19.7909 74 22V98C74 100.209 75.7909 102 78 102H98C100.209 102 102 100.209 102 98V22C102 19.7909 100.209 18 98 18H78Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M41 10C47.6274 10 53 15.3726 53 22V98C53 104.627 47.6274 110 41 110H22C15.3726 110 10 104.627 10 98V22C10 15.3726 15.3726 10 22 10H41ZM98 10C104.627 10 110 15.3726 110 22V98C110 104.627 104.627 110 98 110H79C72.3726 110 67 104.627 67 98V22C67 15.3726 72.3726 10 79 10H98Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
    fill: BoldFill,
  },
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolPauseProps = AvialaIconProps;

export function SymbolPause({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolPauseProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
