/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M60 94C64.4183 94 68 97.5817 68 102C68 106.418 64.4183 110 60 110C55.5817 110 52 106.418 52 102C52 97.5817 55.5817 94 60 94Z" fill="currentColor" /><path d="M60 11C63.34 11 66.0334 13.7336 65.9844 17.0732L64.999 84.0732C64.9588 86.8057 62.7328 89 60 89C57.2672 89 55.0412 86.8057 55.001 84.0732L54.0156 17.0732C53.9666 13.7336 56.66 11 60 11Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 14C62.223 14 64.0165 15.8182 63.9861 18.041L62.9998 90.0411C62.9778 91.679 61.6431 93 60 93C58.3512 93 57.013 91.6698 57.0001 90.024L56.014 18.041C55.9836 15.8182 57.7771 14 60 14ZM64 103C64 105.209 62.2091 107 60 107C57.7909 107 56 105.209 56 103C56 100.791 57.7909 99 60 99C62.2091 99 64 100.791 64 103Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 11.5C56.9396 11.5 54.471 14.0041 54.5147 17.0642L55.5004 86.0643C55.5348 88.5199 57.5362 90.5 60 90.5C62.4683 90.5 64.4724 88.5127 64.4997 86.0509L65.4852 17.0642C65.529 14.0041 63.0604 11.5 60 11.5ZM60 109C63.866 109 67 105.866 67 102C67 98.134 63.866 95 60 95C56.134 95 53 98.134 53 102C53 105.866 56.134 109 60 109Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 13C57.2185 13 54.9749 15.2759 55.0147 18.057L56.0004 87.0571C56.031 89.2399 57.8099 91 60 91C62.1939 91 63.9753 89.2337 63.9997 87.0455L64.9853 18.057C65.025 15.2759 62.7814 13 60 13ZM60 108C63.3137 108 66 105.314 66 102C66 98.6863 63.3137 96 60 96C56.6863 96 54 98.6863 54 102C54 105.314 56.6863 108 60 108Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type SymbolWarningProps = AvialaIconProps;

export function SymbolWarning({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolWarningProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
