/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M60 6C62.7614 6 65 8.23858 65 11V55H109C111.761 55 114 57.2386 114 60C114 62.7614 111.761 65 109 65H65V109C65 111.761 62.7614 114 60 114C57.2386 114 55 111.761 55 109V65H11C8.23858 65 6 62.7614 6 60C6 57.2386 8.23858 55 11 55H55V11C55 8.23858 57.2386 6 60 6Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M63 10C63 8.34315 61.6569 7 60 7C58.3431 7 57 8.34315 57 10V57H10C8.34315 57 7 58.3431 7 60C7 61.6569 8.34315 63 10 63H57V110C57 111.657 58.3431 113 60 113C61.6569 113 63 111.657 63 110V63H110C111.657 63 113 61.6569 113 60C113 58.3431 111.657 57 110 57H63V10Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M64.5 11C64.5 8.51472 62.4853 6.5 60 6.5C57.5147 6.5 55.5 8.51472 55.5 11V55.5H11C8.51472 55.5 6.5 57.5147 6.5 60C6.5 62.4853 8.51472 64.5 11 64.5H55.5V109C55.5 111.485 57.5147 113.5 60 113.5C62.4853 113.5 64.5 111.485 64.5 109V64.5H109C111.485 64.5 113.5 62.4853 113.5 60C113.5 57.5147 111.485 55.5 109 55.5H64.5V11Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M64 11C64 8.79086 62.2091 7 60 7C57.7909 7 56 8.79086 56 11V56H11C8.79086 56 7 57.7909 7 60C7 62.2091 8.79086 64 11 64H56V109C56 111.209 57.7909 113 60 113C62.2091 113 64 111.209 64 109V64H109C111.209 64 113 62.2091 113 60C113 57.7909 111.209 56 109 56H64V11Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type SymbolAddProps = AvialaIconProps;

export function SymbolAdd({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolAddProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
