/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M105.369 71.2803C114.085 66.2863 114.085 53.7137 105.369 48.7197L33.4625 7.52341C24.7959 2.55817 13.9996 8.81554 13.9996 18.8037V101.196C13.9996 111.184 24.7959 117.442 33.4625 112.477L105.369 71.2803ZM100.398 57.3965C102.41 58.5489 102.41 61.451 100.398 62.6035L28.4908 103.8C26.4908 104.946 23.9996 103.501 23.9996 101.196V18.8037C23.9996 16.4987 26.4908 15.0544 28.4908 16.2002L100.398 57.3965Z" fill="currentColor" /></svg>;

const BoldFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14 18.8029C14.0003 8.81501 24.7964 2.55755 33.4629 7.52262L105.369 48.7199C114.086 53.7138 114.086 66.2855 105.369 71.2795L33.4629 112.477C24.7963 117.442 14 111.185 14 101.196V18.8029Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M16 18.8037C16.0002 10.4845 24.8517 5.22356 32.1231 9.0683L32.4678 9.25873L104.375 50.4551C111.751 54.6807 111.751 65.3192 104.375 69.5449L32.4678 110.741C25.1346 114.942 16 109.648 16 101.196V18.8037ZM29.1709 14.2978C25.897 12.7066 22.0002 15.0823 22 18.8037V101.196C22 105.038 26.1521 107.445 29.4854 105.535L101.393 64.3389C104.745 62.418 104.745 57.5818 101.393 55.6611L29.4854 14.4648L29.1709 14.2978Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M16 18.8037C16.0002 10.4845 24.8517 5.22356 32.1231 9.0683L32.4678 9.25873L104.375 50.4551C111.751 54.6807 111.751 65.3192 104.375 69.5449L32.4678 110.741C25.1346 114.942 16 109.648 16 101.196V18.8037Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14.5 18.8043C14.5 9.20031 24.8806 3.18339 33.2139 7.95759L105.121 49.1549C113.502 53.957 113.502 66.0444 105.121 70.8463L33.2139 112.044C24.8808 116.818 14.5003 110.801 14.5 101.197V18.8043ZM28.7402 15.7672C26.4069 14.4304 23.5 16.1151 23.5 18.8043V101.197C23.5004 103.886 26.4071 105.571 28.7402 104.234L100.647 63.0377C102.993 61.6933 102.993 58.3082 100.647 56.9635L28.7402 15.7672Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M14.5 18.8043C14.5 9.20031 24.8806 3.18339 33.2139 7.95759L105.121 49.1549C113.502 53.957 113.502 66.0444 105.121 70.8463L33.2139 112.044C24.8808 116.818 14.5003 110.801 14.5 101.197V18.8043Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M15 18.804C15 9.58438 24.965 3.80818 32.9649 8.39092L104.872 49.5882C112.918 54.1981 112.918 65.8027 104.872 70.4125L32.9658 111.61C24.966 116.193 15.0002 110.416 15 101.197V18.804ZM28.9883 15.3323C26.3217 13.8049 23 15.7308 23 18.804V101.197C23.0002 104.27 26.3218 106.196 28.9883 104.668L100.896 63.471C103.578 61.9345 103.577 58.0663 100.896 56.5296L28.9883 15.3323Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M15 18.804C15 9.58438 24.965 3.80818 32.9649 8.39092L104.872 49.5882C112.918 54.1981 112.918 65.8027 104.872 70.4125L32.9658 111.61C24.966 116.193 15.0002 110.416 15 101.197V18.804Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
    fill: BoldFill,
  },
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolPlayProps = AvialaIconProps;

export function SymbolPlay({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolPlayProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
