/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 3C91.4802 3 117 28.5198 117 60C117 91.4802 91.4802 117 60 117C28.5198 117 3 91.4802 3 60C3 28.5198 28.5198 3 60 3ZM31.0459 97.0234C39.0263 103.273 49.0777 107 60 107C85.9574 107 107 85.9574 107 60C107 49.0777 103.273 39.0263 97.0234 31.0459L31.0459 97.0234ZM60 13C34.0426 13 13 34.0426 13 60C13 71.4328 17.0839 81.9107 23.8701 90.0586L90.0586 23.8701C81.9107 17.0839 71.4328 13 60 13Z" fill="currentColor" /></svg>;

const BoldFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M104.138 23.9316C112.176 33.757 117 46.3149 117 60C117 91.4802 91.4802 117 60 117C46.3149 117 33.757 112.176 23.9316 104.138L104.138 23.9316Z" fill="currentColor" /><path d="M60 3C74.1948 3 87.1774 8.18916 97.1553 16.7734L16.7734 97.1553C8.18916 87.1774 3 74.1948 3 60C3 28.5198 28.5198 3 60 3Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 5C90.3757 5 115 29.6243 115 60C115 90.3757 90.3757 115 60 115C29.6243 115 5 90.3757 5 60C5 29.6243 29.6243 5 60 5ZM27.54 96.7012C36.1843 104.352 47.5483 109 60 109C87.062 109 109 87.062 109 60C109 47.5483 104.352 36.1843 96.7012 27.54L27.54 96.7012ZM60 11C32.938 11 11 32.938 11 60C11 72.4512 15.6473 83.8148 23.2979 92.459L92.459 23.2979C83.8148 15.6473 72.4512 11 60 11Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M100.953 23.2881C109.687 33.0241 115 45.8913 115 60C115 90.3757 90.3757 115 60 115C45.8913 115 33.0241 109.687 23.2881 100.953L100.953 23.2881Z" fill="currentColor" /><path d="M60 5C74.1082 5 86.975 10.3128 96.7109 19.0459L19.0459 96.7109C10.3128 86.975 5 74.1082 5 60C5 29.6243 29.6243 5 60 5Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 3.5C91.2041 3.5 116.5 28.7959 116.5 60C116.5 91.2041 91.2041 116.5 60 116.5C28.7959 116.5 3.5 91.2041 3.5 60C3.5 28.7959 28.7959 3.5 60 3.5ZM30.2969 97.0654C38.4316 103.593 48.7588 107.5 60 107.5C86.2335 107.5 107.5 86.2335 107.5 60C107.5 48.7588 103.593 38.4316 97.0654 30.2969L30.2969 97.0654ZM60 12.5C33.7665 12.5 12.5 33.7665 12.5 60C12.5 71.7513 16.7694 82.504 23.8389 90.7969L90.7969 23.8389C82.504 16.7694 71.7513 12.5 60 12.5Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M103.463 23.8994C111.603 33.6893 116.5 46.2726 116.5 60C116.5 91.2041 91.2041 116.5 60 116.5C46.2726 116.5 33.6893 111.603 23.8994 103.463L103.463 23.8994Z" fill="currentColor" /><path d="M60 3.5C74.237 3.5 87.2439 8.76591 97.1797 17.4561L17.4561 97.1797C8.76591 87.2439 3.5 74.237 3.5 60C3.5 28.7959 28.7959 3.5 60 3.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M60 4C90.9279 4 116 29.0721 116 60C116 90.9279 90.9279 116 60 116C29.0721 116 4 90.9279 4 60C4 29.0721 29.0721 4 60 4ZM29.5498 97.1055C37.8351 103.913 48.44 108 60 108C86.5097 108 108 86.5097 108 60C108 48.44 103.913 37.8351 97.1055 29.5498L29.5498 97.1055ZM60 12C33.4903 12 12 33.4903 12 60C12 72.0696 16.4566 83.097 23.8115 91.5312L91.5312 23.8115C83.097 16.4566 72.0696 12 60 12Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M102.786 23.8691C111.03 33.6215 116 46.2302 116 60C116 90.9279 90.9279 116 60 116C46.2302 116 33.6215 111.03 23.8691 102.786L102.786 23.8691Z" fill="currentColor" /><path d="M60 4C74.279 4 87.3097 9.34428 97.2012 18.1416L18.1416 97.2012C9.34428 87.3097 4 74.279 4 60C4 29.0721 29.0721 4 60 4Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
    fill: BoldFill,
  },
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolNoCircleProps = AvialaIconProps;

export function SymbolNoCircle({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolNoCircleProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
