/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 11C104.075 11 109 15.9249 109 22V98C109 104.075 104.075 109 98 109H22C15.9249 109 11 104.075 11 98V22C11 15.9249 15.9249 11 22 11H98ZM22 17C19.2386 17 17 19.2386 17 22V98C17 100.761 19.2386 103 22 103H98C100.761 103 103 100.761 103 98V22C103 19.2386 100.761 17 98 17H22Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 11C104.075 11 109 15.9249 109 22V98C109 104.075 104.075 109 98 109H22C15.9249 109 11 104.075 11 98V22C11 15.9249 15.9249 11 22 11H98Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 9.5C104.904 9.5 110.5 15.0964 110.5 22V98C110.5 104.904 104.904 110.5 98 110.5H22C15.0964 110.5 9.5 104.904 9.5 98V22C9.5 15.0964 15.0964 9.5 22 9.5H98ZM22 18.5C20.067 18.5 18.5 20.067 18.5 22V98C18.5 99.933 20.067 101.5 22 101.5H98C99.933 101.5 101.5 99.933 101.5 98V22C101.5 20.067 99.933 18.5 98 18.5H22Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 9.5C104.904 9.5 110.5 15.0964 110.5 22V98C110.5 104.904 104.904 110.5 98 110.5H22C15.0964 110.5 9.5 104.904 9.5 98V22C9.5 15.0964 15.0964 9.5 22 9.5H98Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 10C104.627 10 110 15.3726 110 22V98C110 104.627 104.627 110 98 110H22C15.3726 110 10 104.627 10 98V22C10 15.3726 15.3726 10 22 10H98ZM22 18C19.7909 18 18 19.7909 18 22V98C18 100.209 19.7909 102 22 102H98C100.209 102 102 100.209 102 98V22C102 19.7909 100.209 18 98 18H22Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M98 10C104.627 10 110 15.3726 110 22V98C110 104.627 104.627 110 98 110H22C15.3726 110 10 104.627 10 98V22C10 15.3726 15.3726 10 22 10H98Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolEndProps = AvialaIconProps;

export function SymbolEnd({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolEndProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
