/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 35.5C63.0519 35.5 65.5194 37.9864 65.4961 41.0381L65.0391 100.5H70C72.7614 100.5 75 102.739 75 105.5C75 108.261 72.7614 110.5 70 110.5H50C47.2386 110.5 45 108.261 45 105.5C45 102.739 47.2386 100.5 50 100.5H54.9609L54.5381 45.5H53C50.2386 45.5 48 43.2614 48 40.5C48 37.7386 50.2386 35.5 53 35.5H60Z" fill="currentColor" /><path d="M60 12C64.9706 12 69 16.0294 69 21C69 25.9706 64.9706 30 60 30C55.0294 30 51 25.9706 51 21C51 16.0294 55.0294 12 60 12Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 34C60.0534 34 60.1065 34.0012 60.1592 34.0039C62.0258 34.0876 63.5096 35.6341 63.4961 37.5215L63.0215 103H70C71.6569 103 73 104.343 73 106C73 107.657 71.6569 109 70 109H50C48.3431 109 47 107.657 47 106C47 104.343 48.3431 103 50 103H56.9785L56.5215 40H53C51.3431 40 50 38.6569 50 37C50 35.3431 51.3431 34 53 34H60ZM60 15C63.3137 15 66 17.6863 66 21C66 24.3137 63.3137 27 60 27C56.6863 27 54 24.3137 54 21C54 17.6863 56.6863 15 60 15Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 35C60.0793 35 60.1581 35.0018 60.2363 35.0059C62.9003 35.1299 65.0165 37.3394 64.9961 40.0342L64.5342 101H70C72.4853 101 74.5 103.015 74.5 105.5C74.5 107.985 72.4853 110 70 110H50C47.5147 110 45.5 107.985 45.5 105.5C45.5 103.015 47.5147 101 50 101H55.4658L55.0342 44H53C50.5147 44 48.5 41.9853 48.5 39.5C48.5 37.0147 50.5147 35 53 35H60ZM60 13C64.4183 13 68 16.5817 68 21C68 25.4183 64.4183 29 60 29C55.5817 29 52 25.4183 52 21C52 16.5817 55.5817 13 60 13Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M60 35C60.0711 35 60.1418 35.0012 60.2119 35.0049C62.6097 35.1162 64.5145 37.1049 64.4961 39.5303L64.0303 101H70C72.2091 101 74 102.791 74 105C74 107.209 72.2091 109 70 109H50C47.7909 109 46 107.209 46 105C46 102.791 47.7909 101 50 101H55.9697L55.5303 43H53C50.7909 43 49 41.2091 49 39C49 36.7909 50.7909 35 53 35H60ZM60 14C63.866 14 67 17.134 67 21C67 24.866 63.866 28 60 28C56.134 28 53 24.866 53 21C53 17.134 56.134 14 60 14Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type SymbolInformationProps = AvialaIconProps;

export function SymbolInformation({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolInformationProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
