/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M50.4431 61.2245H27.4073C26.5174 61.2245 26.0708 60.1495 26.6986 59.5189L74.8013 11.2086C75.4874 10.5195 76.6539 11.1161 76.4967 12.0758L68.6389 60.0629C68.5392 60.6716 69.009 61.2245 69.6257 61.2245H93.2359C94.1715 61.2245 94.5948 62.3945 93.8757 62.9931L37.6904 109.761C36.9174 110.404 35.7851 109.632 36.1015 108.678L51.3923 62.5391C51.6068 61.8919 51.1249 61.2245 50.4431 61.2245Z" stroke="currentColor" strokeWidth={10} strokeLinecap="round" /></svg>;

const BoldFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M71.2572 7.68088C75.3742 3.54618 82.3727 7.12588 81.4301 12.884L74.3334 56.2239H93.2357C98.8489 56.2242 101.388 63.245 97.0736 66.8362L40.889 113.604C36.2512 117.464 29.4567 112.833 31.3549 107.105L44.9037 66.2239H27.4066C22.0677 66.2236 19.3875 59.7739 23.1547 55.9905L71.2572 7.68088Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M72.6503 9.04978C75.5073 6.49024 80.052 9.08943 79.2099 12.9053L69.1474 58.5H93.2216C96.9702 58.5003 98.6595 63.1942 95.7705 65.583L41.6738 110.314C38.6703 112.797 34.2503 109.956 35.2617 106.192L46.4667 64.5H25.4628C21.8722 64.4998 20.1003 60.1349 22.6747 57.6318L72.5156 9.17576L72.6503 9.04978ZM30.3886 58.5H49.0751C51.7064 58.5001 53.6212 60.997 52.9384 63.5381L42.6845 101.691L87.665 64.5H66.6582C64.1018 64.4998 62.2021 62.1341 62.7529 59.6377L71.914 18.1289L30.3886 58.5Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M72.6503 9.04978C75.5073 6.49025 80.052 9.08942 79.2099 12.9053L69.1474 58.5H93.2216C96.9702 58.5003 98.6595 63.1942 95.7705 65.583L41.6738 110.313C38.6703 112.797 34.2503 109.956 35.2617 106.192L46.4667 64.5H25.4628C21.8722 64.4998 20.1003 60.1349 22.6747 57.6318L72.5156 9.17576L72.6503 9.04978Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M71.7902 7.86105C75.5839 4.34649 81.787 7.60686 80.9367 12.8025L73.7443 56.7243H93.2346C98.3802 56.7243 100.708 63.1599 96.7531 66.4519L40.5686 113.219C36.3172 116.758 30.0882 112.512 31.8284 107.261L45.594 65.7243H27.4065C22.5124 65.7242 20.0558 59.8116 23.509 56.3435L71.6115 8.03292L71.7902 7.86105ZM35.8303 56.7243H50.4416C54.1916 56.7243 56.8419 60.3952 55.6623 63.9548L44.2258 98.4646L83.5588 65.7243H69.6242C66.2322 65.724 63.6485 62.6831 64.1965 59.3357L70.2922 22.113L35.8303 56.7243Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M71.7902 7.86105C75.5839 4.34649 81.787 7.60686 80.9367 12.8025L73.7443 56.7243H93.2346C98.3802 56.7243 100.708 63.1599 96.7531 66.4519L40.5686 113.219C36.3172 116.758 30.0882 112.512 31.8284 107.261L45.594 65.7243H27.4065C22.5124 65.7242 20.0557 59.8116 23.509 56.3435L71.6115 8.03293L71.7902 7.86105Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M71.9374 7.37291C75.4174 3.94439 81.2439 7.02821 80.3652 11.8339L72.246 56.2246H93.2002C97.8976 56.2249 100.002 62.1162 96.3682 65.0927L39.2928 111.836C35.3828 115.038 29.7331 111.08 31.4071 106.312L46.1835 64.2246H26.4393C21.9671 64.2245 19.7448 58.802 22.9305 55.663L71.9374 7.37291ZM33.7576 56.2246H50.4169C53.8627 56.225 56.2759 59.6295 55.1347 62.8808L42.4989 98.8692L84.8017 64.2246H68.6474C65.526 64.2244 63.168 61.3957 63.7294 58.3251L70.788 19.7372L33.7576 56.2246Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M72.0572 7.30049C75.5396 4.07636 81.2234 7.13214 80.3541 11.8864L72.2447 56.2243H93.2339C97.9117 56.2243 100.028 62.0743 96.4331 65.0671L40.2477 111.835C36.3828 115.052 30.7204 111.192 32.3024 106.419L46.2858 64.2243H27.4059C22.957 64.224 20.7229 58.8488 23.862 55.696L71.8922 7.45869L72.0572 7.30049Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
    fill: BoldFill,
  },
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolFastProps = AvialaIconProps;

export function SymbolFast({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolFastProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
