/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M103.465 47.4652C105.418 45.5126 108.583 45.5126 110.536 47.4652C112.488 49.4178 112.488 52.583 110.536 54.5355L54.5358 110.536C52.5833 112.488 49.4181 112.488 47.4654 110.536C45.5128 108.583 45.5128 105.418 47.4654 103.465L103.465 47.4652Z" fill="currentColor" /><path d="M100.465 8.4652C102.418 6.51258 105.583 6.51258 107.536 8.4652C109.488 10.4178 109.488 13.583 107.536 15.5355L15.5358 107.536C13.5833 109.488 10.4181 109.488 8.46544 107.536C6.51282 105.583 6.51282 102.418 8.46544 100.465L100.465 8.4652Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M106.121 14.1213C107.293 12.9497 107.293 11.0503 106.121 9.87868C104.95 8.70711 103.05 8.70711 101.879 9.87868L9.87868 101.879C8.70711 103.05 8.70711 104.95 9.87868 106.121C11.0503 107.293 12.9497 107.293 14.1213 106.121L106.121 14.1213ZM109.121 53.1213C110.293 51.9497 110.293 50.0503 109.121 48.8787C107.95 47.7071 106.05 47.7071 104.879 48.8787L48.8787 104.879C47.7071 106.05 47.7071 107.95 48.8787 109.121C50.0503 110.293 51.9497 110.293 53.1213 109.121L109.121 53.1213Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M107.182 15.182C108.939 13.4246 108.939 10.5754 107.182 8.81802C105.425 7.06066 102.575 7.06066 100.818 8.81802L8.81802 100.818C7.06066 102.575 7.06066 105.425 8.81802 107.182C10.5754 108.939 13.4246 108.939 15.182 107.182L107.182 15.182ZM110.182 54.182C111.939 52.4246 111.939 49.5754 110.182 47.818C108.425 46.0607 105.575 46.0607 103.818 47.818L47.818 103.818C46.0607 105.575 46.0607 108.425 47.818 110.182C49.5754 111.939 52.4246 111.939 54.182 110.182L110.182 54.182Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M106.828 14.8284C108.391 13.2663 108.391 10.7337 106.828 9.17157C105.266 7.60948 102.734 7.60948 101.172 9.17157L9.17157 101.172C7.60948 102.734 7.60948 105.266 9.17157 106.828C10.7337 108.391 13.2663 108.391 14.8284 106.828L106.828 14.8284ZM109.828 53.8284C111.391 52.2663 111.391 49.7337 109.828 48.1716C108.266 46.6095 105.734 46.6095 104.172 48.1716L48.1716 104.172C46.6095 105.734 46.6095 108.266 48.1716 109.828C49.7337 111.391 52.2663 111.391 53.8284 109.828L109.828 53.8284Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type SymbolResizeProps = AvialaIconProps;

export function SymbolResize({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolResizeProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
