/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 23.8334C104.075 23.8334 109 28.7582 109 34.8334V110.833C109 116.909 104.075 121.833 98 121.833H22C15.9249 121.833 11 116.909 11 110.833V34.8334C11 28.7582 15.9249 23.8334 22 23.8334H98ZM22 29.8334C19.2386 29.8334 17 32.072 17 34.8334V110.833C17 113.595 19.2386 115.833 22 115.833H98C100.761 115.833 103 113.595 103 110.833V34.8334C103 32.0719 100.761 29.8334 98 29.8334H22Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 23.8334C104.075 23.8334 109 28.7582 109 34.8334V110.833C109 116.909 104.075 121.833 98 121.833H22C15.9249 121.833 11 116.909 11 110.833V34.8334C11 28.7582 15.9249 23.8334 22 23.8334H98Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 20.5834C104.904 20.5834 110.5 26.1798 110.5 33.0834V109.083C110.5 115.987 104.904 121.583 98 121.583H22C15.0964 121.583 9.5 115.987 9.5 109.083V33.0834C9.5 26.1798 15.0964 20.5834 22 20.5834H98ZM22 29.5834C20.067 29.5834 18.5 31.1504 18.5 33.0834V109.083C18.5 111.016 20.067 112.583 22 112.583H98C99.933 112.583 101.5 111.016 101.5 109.083V33.0834C101.5 31.1504 99.933 29.5834 98 29.5834H22Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 20.5834C104.904 20.5834 110.5 26.1798 110.5 33.0834V109.083C110.5 115.987 104.904 121.583 98 121.583H22C15.0964 121.583 9.5 115.987 9.5 109.083V33.0834C9.5 26.1798 15.0964 20.5834 22 20.5834H98Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 21.6666C104.627 21.6666 110 27.0392 110 33.6666V109.667C110 116.294 104.627 121.667 98 121.667H22C15.3726 121.667 10 116.294 10 109.667V33.6666C10 27.0392 15.3726 21.6666 22 21.6666H98ZM22 29.6666C19.7909 29.6666 18 31.4575 18 33.6666V109.667C18 111.876 19.7909 113.667 22 113.667H98C100.209 113.667 102 111.876 102 109.667V33.6666C102 31.4575 100.209 29.6666 98 29.6666H22Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 260" {...props}><path d="M98 21.6666C104.627 21.6666 110 27.0392 110 33.6666V109.667C110 116.294 104.627 121.667 98 121.667H22C15.3726 121.667 10 116.294 10 109.667V33.6666C10 27.0392 15.3726 21.6666 22 21.6666H98Z" fill="currentColor" /></svg>;

const variants = {
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolEndProps = AvialaIconProps;

export function SymbolEnd({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolEndProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
