/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M92.0121 76.541C104.503 76.541 109.806 60.6412 99.8149 53.1436L41.8031 9.6084C33.2336 3.17738 21.0004 9.29158 21.0004 20.0059L21.0004 110C21.0004 112.761 23.239 115 26.0004 115C28.7618 115 31.0004 112.761 31.0004 110V76.541H92.0121ZM31.0004 66.541L31.0004 20.0059C31.0004 17.5333 33.8236 16.1224 35.8012 17.6064L93.8129 61.1416C96.1185 62.8718 94.8947 66.541 92.0121 66.541H31.0004Z" fill="currentColor" /></svg>;

const BoldFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21 20.0059C21 9.29162 33.2332 3.17742 41.8027 9.60843L99.8145 53.1436C109.805 60.6413 104.503 76.541 92.0117 76.541H31V110C31 112.761 28.7614 115 26 115C23.2386 115 21 112.761 21 110V20.0059Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M23 18.2587C23.0002 9.12969 33.4791 3.97293 40.7119 9.54287L98.2129 53.8261C106.532 60.2329 102.001 73.5408 91.501 73.541H29V111L28.9961 111.154C28.9159 112.74 27.6052 114 26 114C24.3431 114 23 112.657 23 111V18.2587ZM37.0508 14.2968C33.7632 11.7652 29.0002 14.1093 29 18.2587V67.541H91.501C96.2736 67.5408 98.3329 61.4922 94.5518 58.58L37.0508 14.2968Z" fill="currentColor" /></svg>;

const LightFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M23 18.2587C23.0002 9.12969 33.4791 3.97293 40.7119 9.54287L98.2129 53.8261C106.532 60.2329 102.001 73.5408 91.501 73.541H29V111C29 112.657 27.6569 114 26 114C24.3431 114 23 112.657 23 111V18.2587Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21.5 20.0058C21.5002 9.70386 33.263 3.82449 41.5029 10.0077L99.5146 53.5439C109.121 60.7532 104.022 76.041 92.0117 76.041H30.5V110L30.4941 110.231C30.3738 112.609 28.4077 114.5 26 114.5C23.5147 114.5 21.5 112.485 21.5 110V20.0058ZM36.1006 17.206C33.7935 15.4754 30.5002 17.1216 30.5 20.0058V67.041H92.0117C95.3747 67.041 96.8021 62.7608 94.1123 60.7421L36.1006 17.206Z" fill="currentColor" /></svg>;

const MediumFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21.5 20.0058C21.5002 9.70386 33.263 3.82449 41.5029 10.0077L99.5146 53.5439C109.121 60.7532 104.022 76.041 92.0117 76.041H30.5V110C30.5 112.485 28.4853 114.5 26 114.5C23.5147 114.5 21.5 112.485 21.5 110V20.0058Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M22 20.0058C22.0001 10.1158 33.2928 4.47181 41.2031 10.4082L99.2148 53.9433C108.437 60.8643 103.542 75.541 92.0117 75.541H30V111L29.9951 111.206C29.8879 113.319 28.1401 115 26 115C23.7909 115 22 113.209 22 111V20.0058ZM36.4014 16.8066C33.7646 14.8279 30.0001 16.7092 30 20.0058V67.541H92.0117C95.8551 67.541 97.4871 62.6488 94.4131 60.3418L36.4014 16.8066Z" fill="currentColor" /></svg>;

const RegularFill = (props: SVGProps<SVGSVGElement>) => <svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M22 20.0058C22.0001 10.1158 33.2928 4.47181 41.2031 10.4082L99.2148 53.9433C108.437 60.8643 103.542 75.541 92.0117 75.541H30V111C30 113.209 28.2091 115 26 115C23.7909 115 22 113.209 22 111V20.0058Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
    fill: BoldFill,
  },
  Light: {
    default: LightDefault,
    fill: LightFill,
  },
  Medium: {
    default: MediumDefault,
    fill: MediumFill,
  },
  Regular: {
    default: RegularDefault,
    fill: RegularFill,
  },
} as const;

export type SymbolFlagProps = AvialaIconProps;

export function SymbolFlag({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolFlagProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
