/** Auto-generated by scripts/build-icons.mjs — do not edit manually */
import type { SVGProps } from "react";
import { applyAvialaIconProps } from "../icon-size";
import { resolveIconVariant } from "../resolve-variant";
import type { AvialaIconProps } from "../types";
import { DEFAULT_ICON_MODE, DEFAULT_ICON_THICKNESS } from "../types";

const BoldDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M19 48C25.6274 48 31 53.3726 31 60C31 66.6274 25.6274 72 19 72C12.3726 72 7 66.6274 7 60C7 53.3726 12.3726 48 19 48Z" fill="currentColor" /><path d="M60 48C66.6274 48 72 53.3726 72 60C72 66.6274 66.6274 72 60 72C53.3726 72 48 66.6274 48 60C48 53.3726 53.3726 48 60 48Z" fill="currentColor" /><path d="M101 48C107.627 48 113 53.3726 113 60C113 66.6274 107.627 72 101 72C94.3726 72 89 66.6274 89 60C89 53.3726 94.3726 48 101 48Z" fill="currentColor" /></svg>;

const LightDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M20 51C24.9706 51 29 55.0294 29 60C29 64.9706 24.9706 69 20 69C15.0294 69 11 64.9706 11 60C11 55.0294 15.0294 51 20 51ZM60 51C64.9706 51 69 55.0294 69 60C69 64.9706 64.9706 69 60 69C55.0294 69 51 64.9706 51 60C51 55.0294 55.0294 51 60 51ZM100 51C104.971 51 109 55.0294 109 60C109 64.9706 104.971 69 100 69C95.0294 69 91 64.9706 91 60C91 55.0294 95.0294 51 100 51Z" fill="currentColor" /></svg>;

const MediumDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M19 48.5C25.3513 48.5 30.5 53.6487 30.5 60C30.5 66.3513 25.3513 71.5 19 71.5C12.6487 71.5 7.5 66.3513 7.5 60C7.5 53.6487 12.6487 48.5 19 48.5ZM60 48.5C66.3513 48.5 71.5 53.6487 71.5 60C71.5 66.3513 66.3513 71.5 60 71.5C53.6487 71.5 48.5 66.3513 48.5 60C48.5 53.6487 53.6487 48.5 60 48.5ZM101 48.5C107.351 48.5 112.5 53.6487 112.5 60C112.5 66.3513 107.351 71.5 101 71.5C94.6487 71.5 89.5 66.3513 89.5 60C89.5 53.6487 94.6487 48.5 101 48.5Z" fill="currentColor" /></svg>;

const RegularDefault = (props: SVGProps<SVGSVGElement>) => <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" {...props}><path d="M19 50C24.5228 50 29 54.4772 29 60C29 65.5228 24.5228 70 19 70C13.4772 70 9 65.5228 9 60C9 54.4772 13.4772 50 19 50ZM60 50C65.5228 50 70 54.4772 70 60C70 65.5228 65.5228 70 60 70C54.4772 70 50 65.5228 50 60C50 54.4772 54.4772 50 60 50ZM101 50C106.523 50 111 54.4772 111 60C111 65.5228 106.523 70 101 70C95.4771 70 91 65.5228 91 60C91 54.4772 95.4771 50 101 50Z" fill="currentColor" /></svg>;

const variants = {
  Bold: {
    default: BoldDefault,
  },
  Light: {
    default: LightDefault,
  },
  Medium: {
    default: MediumDefault,
  },
  Regular: {
    default: RegularDefault,
  },
} as const;

export type SymbolMoreProps = AvialaIconProps;

export function SymbolMore({
  thickness = DEFAULT_ICON_THICKNESS,
  mode = DEFAULT_ICON_MODE,
  ...props
}: SymbolMoreProps) {
  const Variant = resolveIconVariant(variants, thickness, mode);
  return <Variant {...applyAvialaIconProps({ thickness, mode, ...props })} />;
}
